spring.application.name=vix-health-system

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/VIX-health-system
spring.datasource.username=postgres
spring.datasource.password=LA_TUA_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false