SET MODE PostgreSQL;

-- =====================================================
-- MEDICAL FACILITIES
-- =====================================================

CREATE TABLE IF NOT EXISTS MedicalFacilities (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name VARCHAR(100) NOT NULL,
                                   type VARCHAR(30) NOT NULL,
                                   latitude DOUBLE PRECISION,
                                   longitude DOUBLE PRECISION,
                                   email VARCHAR(100),
                                   phone VARCHAR(30)
);


-- =====================================================
-- STORAGES
-- =====================================================

CREATE TABLE IF NOT EXISTS Storages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          facility_id BIGINT NOT NULL UNIQUE,

                          CONSTRAINT fk_storage_facility
                              FOREIGN KEY (facility_id)
                                  REFERENCES MedicalFacilities(id)
);

-- =====================================================
-- RESOURCES
-- =====================================================

CREATE TABLE IF NOT EXISTS Resources (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(100) NOT NULL,
                           description TEXT,
                           price DECIMAL(10,2) NOT NULL
);

-- =====================================================
-- STORAGE RESOURCES (MANY TO MANY)
-- =====================================================

CREATE TABLE IF NOT EXISTS StorageResources (
                                  storage_id BIGINT NOT NULL,
                                  resource_id BIGINT NOT NULL,
                                  quantity INT NOT NULL DEFAULT 0,

                                  PRIMARY KEY (storage_id, resource_id),

                                  CONSTRAINT fk_sr_storage
                                      FOREIGN KEY (storage_id)
                                          REFERENCES Storages(id),

                                  CONSTRAINT fk_sr_resource
                                      FOREIGN KEY (resource_id)
                                          REFERENCES Resources(id)
);

-- =====================================================
-- DEPARTMENTS
-- =====================================================

CREATE TABLE IF NOT EXISTS Departments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             facility_id BIGINT NOT NULL,

                             name VARCHAR(100) NOT NULL,
                             description TEXT,
                             email VARCHAR(100),
                             phone VARCHAR(30),

                             CONSTRAINT fk_department_facility
                                 FOREIGN KEY (facility_id)
                                     REFERENCES MedicalFacilities(id)
);

-- =====================================================
-- EMPLOYEES (SINGLE TABLE INHERITANCE)
-- =====================================================

CREATE TABLE IF NOT EXISTS Employees (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           firebase_uid VARCHAR(255) UNIQUE,

                           type VARCHAR(30) NOT NULL,

                           name VARCHAR(100) NOT NULL,
                           surname VARCHAR(100) NOT NULL,

                           birth_date DATE,
                           birth_place VARCHAR(100),
                           gender CHAR(1),

                           email VARCHAR(100),
                           phone VARCHAR(30),

                           hire_date DATE NOT NULL,

                           department_id BIGINT,

                           specialty VARCHAR(100),
                           license_number VARCHAR(100),
                           secretary_type VARCHAR(100),

                           CONSTRAINT fk_employee_department
                               FOREIGN KEY (department_id)
                                   REFERENCES Departments(id)
);


-- =====================================================
-- ROOMS
-- =====================================================

CREATE TABLE IF NOT EXISTS Rooms (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       facility_id BIGINT NOT NULL,

                       room_number VARCHAR(20) NOT NULL,
                       type VARCHAR(30) NOT NULL,

                       specialization VARCHAR(100) ,
                       beds_count INT,
                       employee_id BIGINT UNIQUE,

                       CONSTRAINT fk_room_facility
                           FOREIGN KEY (facility_id)
                               REFERENCES MedicalFacilities(id),

                       CONSTRAINT fk_room_employee
                           FOREIGN KEY (employee_id)
                               REFERENCES Employees(id)
);

-- =====================================================
-- PATIENTS
-- =====================================================

CREATE TABLE IF NOT EXISTS Patients (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          fiscal_code VARCHAR(16) NOT NULL UNIQUE,

                          name VARCHAR(100) NOT NULL,
                          surname VARCHAR(100) NOT NULL,

                          birth_date DATE,
                          birth_place VARCHAR(100),
                          gender CHAR(1),

                          email VARCHAR(100),
                          phone VARCHAR(30)
);

-- =====================================================
-- MEDICAL RECORDS
-- =====================================================

CREATE TABLE IF NOT EXISTS MedicalRecords (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                patient_id BIGINT NOT NULL UNIQUE,

                                height FLOAT,
                                weight FLOAT,
                                blood_type VARCHAR(5),
                                allergies TEXT,
                                vaccines TEXT,

                                CONSTRAINT fk_medical_record_patient
                                    FOREIGN KEY (patient_id)
                                        REFERENCES Patients(id)
);

-- =====================================================
-- MEDICAL CONDITIONS
-- =====================================================

CREATE TABLE IF NOT EXISTS MedicalConditions (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                   medical_record_id BIGINT NOT NULL,

                                   name VARCHAR(100) NOT NULL,
                                   diagnosis_date DATE,
                                   type VARCHAR(100),
                                   description TEXT,
                                   treatment TEXT,

                                   CONSTRAINT fk_condition_medical_record
                                       FOREIGN KEY (medical_record_id)
                                           REFERENCES MedicalRecords(id)
);

-- =====================================================
-- PRESCRIPTIONS
-- =====================================================

CREATE TABLE IF NOT EXISTS Prescriptions (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               medical_record_id BIGINT NOT NULL,
                               medical_specialist_id BIGINT NOT NULL,

                               prescription_date TIMESTAMP NOT NULL,
                               medication VARCHAR(255) NOT NULL,

                               CONSTRAINT fk_prescription_medical_record
                                   FOREIGN KEY (medical_record_id)
                                       REFERENCES MedicalRecords(id),

                               CONSTRAINT fk_prescription_specialist
                                   FOREIGN KEY (medical_specialist_id)
                                       REFERENCES Employees(id)
);

-- =====================================================
-- SURGERIES
-- =====================================================

CREATE TABLE IF NOT EXISTS Surgeries (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           medical_record_id BIGINT NOT NULL,
                           specialized_room_id BIGINT NOT NULL,

                           surgery_date TIMESTAMP NOT NULL,
                           name VARCHAR(100) NOT NULL,
                           description TEXT,

                           CONSTRAINT fk_surgery_medical_record
                               FOREIGN KEY (medical_record_id)
                                   REFERENCES MedicalRecords(id),

                           CONSTRAINT fk_surgery_specialized_room
                               FOREIGN KEY (specialized_room_id)
                                   REFERENCES Rooms(id)
);

-- =====================================================
-- MACHINES
-- =====================================================

CREATE TABLE IF NOT EXISTS Machines (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          specialized_room_id BIGINT NOT NULL,

                          name VARCHAR(100) NOT NULL,
                          status VARCHAR(50),

                          CONSTRAINT fk_machine_room
                              FOREIGN KEY (specialized_room_id)
                                  REFERENCES Rooms(id)
);

-- =====================================================
-- ROOM PATIENTS (OCCUPAZIONE STANZE)
-- =====================================================

CREATE TABLE IF NOT EXISTS RoomPatients (
                              room_id BIGINT NOT NULL,
                              patient_id BIGINT NOT NULL,

                              PRIMARY KEY (room_id, patient_id),

                              CONSTRAINT fk_room_patient_room
                                  FOREIGN KEY (room_id)
                                      REFERENCES Rooms(id),

                              CONSTRAINT fk_room_patient_patient
                                  FOREIGN KEY (patient_id)
                                      REFERENCES Patients(id)
);
