VIX Health System: MedicalRecordService Class Reference
MedicalRecordService Class Reference
Manages patient medical records : creation and appending of diagnoses, prescriptions, and exam results.
Public Member Functions
MedicalRecordService (MedicalRecordRepository medicalRecordRepository, PatientRepository patientRepository, EmployeeRepository employeeRepository, AuditService auditService)
Constructs the service with all required repositories and collaborators.
MedicalRecord getMedicalRecordByPatientId (Long patientId)
Returns the medical record for the given patient, throwing when absent.
Patient getPatientWithMedicalRecord (Long patientId)
Loads a patient and touches their medical record proxy to force initialisation.
MedicalRecord createMedicalRecord (Long patientId, Float height, Float weight, String bloodType)
Creates and links a new MedicalRecord for a patient.
void addDiagnosis (Long patientId, String diagnosisName, String description, String severity)
Appends a diagnosis to the patient's medical record, creating the record first if it does not exist.
void addPrescription (Long patientId, Long medicalSpecialistId, String medication)
Issues a prescription for the patient via the prescribing specialist's domain method.
void addExamResult (Long patientId, String examType, String result, String notes)
Records an exam result in the patient's medical record.
List< MedicalCondition > getConditions (Long patientId)
Returns all medical conditions on record for the given patient.
List< Prescription > getPrescriptions (Long patientId)
Returns all prescriptions issued to the given patient.
List< Surgery > getSurgeries (Long patientId)
Returns all surgeries recorded for the given patient.
Detailed Description
Manages patient medical records : creation and appending of diagnoses, prescriptions, and exam results.
Annotated @Transactional(readOnly=true) at the class level; write methods override with @Transactional.
All mutations are recorded via AuditService to satisfy NFR02 (traceability). When a patient has no record yet, write operations auto-create one rather than failing.
Prescription issuance delegates to vixhealthsystem.model.person.employee.MedicalSpecialist#appPrescriptionForPatient so that domain invariants are enforced by the model layer.
See also
PatientService
vixhealthsystem.model.medical.MedicalRecord
AuditService
Definition at line 39 of file MedicalRecordService.java.
Constructor & Destructor Documentation
MedicalRecordService()
MedicalRecordService (MedicalRecordRepository medicalRecordRepository, PatientRepository patientRepository, EmployeeRepository employeeRepository, AuditService auditService)
Constructs the service with all required repositories and collaborators.
Parameters
medicalRecordRepository Persistence layer for MedicalRecord entities.
patientRepository Used to load and save the owning Patient.
employeeRepository Needed to resolve the prescribing specialist by ID.
auditService Records every clinical write for traceability (NFR02).
Definition at line 63 of file MedicalRecordService.java.
Member Function Documentation
getMedicalRecordByPatientId()
MedicalRecord getMedicalRecordByPatientId (Long patientId)
Returns the medical record for the given patient, throwing when absent.
Parameters
patientId ID of the patient.
Returns
The patient's MedicalRecord; never null.
Exceptions
RuntimeException When no medical record exists for the patient.
Definition at line 84 of file MedicalRecordService.java.
Referenced by getConditions(), getPrescriptions(), and getSurgeries().
getPatientWithMedicalRecord()
Patient getPatientWithMedicalRecord (Long patientId)
Loads a patient and touches their medical record proxy to force initialisation.
JPA lazy-loading means the record may still be a proxy after findById; this method ensures the proxy is initialised before the session closes.
Parameters
patientId ID of the patient to load.
Returns
The Patient with the medicalRecord association initialised.
Exceptions
RuntimeException When no patient with patientId exists.
Definition at line 99 of file MedicalRecordService.java.
Referenced by addDiagnosis(), addExamResult(), and addPrescription().
createMedicalRecord()
MedicalRecord createMedicalRecord (Long patientId, Float height, Float weight, String bloodType)
Creates and links a new MedicalRecord for a patient.
All three metric parameters are optional; pass null when not yet known. Allergies and vaccines are initialised to empty strings to avoid null-checks downstream.
Parameters
patientId ID of the patient who owns the record.
height Patient height in centimetres; may be null.
weight Patient weight in kilograms; may be null.
bloodType ABO+Rh blood group string (e.g., "A+"); may be null.
Returns
The persisted MedicalRecord with a generated ID.
Exceptions
RuntimeException When no patient with patientId exists.
Definition at line 129 of file MedicalRecordService.java.
Referenced by addDiagnosis(), addExamResult(), and addPrescription().
addDiagnosis()
void addDiagnosis (Long patientId, String diagnosisName, String description, String severity)
Appends a diagnosis to the patient's medical record, creating the record first if it does not exist.
Parameters
patientId ID of the patient to diagnose.
diagnosisName Short clinical label for the condition.
description Detailed clinical notes.
severity Severity tier (e.g., "MILD", "SEVERE").
Exceptions
RuntimeException When no patient with patientId exists.
Definition at line 159 of file MedicalRecordService.java.
References MedicalRecord.addCondition(), createMedicalRecord(), and getPatientWithMedicalRecord().
addPrescription()
void addPrescription (Long patientId, Long medicalSpecialistId, String medication)
Issues a prescription for the patient via the prescribing specialist's domain method.
Delegates to vixhealthsystem.model.person.employee.MedicalSpecialist#appPrescriptionForPatient so that the specialist back-reference on the Prescription is set correctly. Auto-creates a medical record when the patient has none.
Parameters
patientId ID of the patient receiving the prescription.
medicalSpecialistId ID of the issuing MedicalSpecialist.
medication Name or description of the prescribed medication.
Exceptions
RuntimeException When the patient or specialist cannot be found, or the employee ID does not resolve to a MedicalSpecialist.
Definition at line 194 of file MedicalRecordService.java.
References MedicalSpecialist.appPrescriptionForPatient(), createMedicalRecord(), and getPatientWithMedicalRecord().
addExamResult()
void addExamResult (Long patientId, String examType, String result, String notes)
Records an exam result in the patient's medical record.
Exam results are modelled as MedicalCondition entries with type = "EXAM_RESULT" because no separate exam-result entity exists yet. Auto-creates a medical record when the patient has none.
Parameters
patientId ID of the patient.
examType Type of examination (e.g., "Blood Test", "MRI").
result The outcome of the exam (e.g., "Normal", numeric values).
notes Optional additional clinical notes; may be null or blank.
Exceptions
RuntimeException When no patient with patientId exists.
Definition at line 235 of file MedicalRecordService.java.
References MedicalRecord.addCondition(), createMedicalRecord(), and getPatientWithMedicalRecord().
getConditions()
List< MedicalCondition > getConditions (Long patientId)
Returns all medical conditions on record for the given patient.
Parameters
patientId ID of the patient.
Returns
Non-null list of MedicalCondition entries.
Exceptions
RuntimeException When no medical record exists for the patient.
Definition at line 271 of file MedicalRecordService.java.
References getMedicalRecordByPatientId().
getPrescriptions()
List< Prescription > getPrescriptions (Long patientId)
Returns all prescriptions issued to the given patient.
Parameters
patientId ID of the patient.
Returns
Non-null list of Prescription entries.
Exceptions
RuntimeException When no medical record exists for the patient.
Definition at line 283 of file MedicalRecordService.java.
References getMedicalRecordByPatientId().
getSurgeries()
List< Surgery > getSurgeries (Long patientId)
Returns all surgeries recorded for the given patient.
Parameters
patientId ID of the patient.
Returns
Non-null list of Surgery entries.
Exceptions
RuntimeException When no medical record exists for the patient.
Definition at line 295 of file MedicalRecordService.java.
References getMedicalRecordByPatientId().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/medical/MedicalRecordService.java