VIX Health System: ResourceTakeLogStore Class Reference
ResourceTakeLogStore Class Reference
JSON-backed append log that records every resource takeout event performed by employees.
Classes
class Entry
Immutable snapshot of a single resource takeout event.
Public Member Functions
ResourceTakeLogStore ()
Initialises the Jackson mapper with Java-time support and ensures the backing JSON file exists on disk.
synchronized List< Entry > getAll ()
Returns all log entries sorted newest-first.
synchronized List< Entry > getByEmployee (Long employeeId)
Returns all log entries for a specific employee, newest-first.
synchronized void log (Long employeeId, String employeeName, String employeeRole, Long resourceId, String resourceName, Long storageId, int quantity)
Prepends a new takeout entry to the log file.
Detailed Description
JSON-backed append log that records every resource takeout event performed by employees.
Entries are stored in src/main/resources/storage/resource-take-logs.json and are sorted newest-first on retrieval. All public methods are synchronized to prevent concurrent write corruption from multi-threaded request handling.
Used by InventoryService#removeResourceFromStorage(com.nvivx.vixhealthsystem.model.person.employee.Employee, Long, int) to maintain a separate, human-readable consumption audit trail alongside the main com.nvivx.vixhealthsystem.service.AuditService log.
See also
InventoryService
Definition at line 29 of file ResourceTakeLogStore.java.
Member Function Documentation
getAll()
synchronized List< Entry > getAll ()
Returns all log entries sorted newest-first.
Returns
Mutable list of entries; empty when the log file is absent or empty.
Definition at line 133 of file ResourceTakeLogStore.java.
Referenced by getByEmployee(), and log().
getByEmployee()
synchronized List< Entry > getByEmployee (Long employeeId)
Returns all log entries for a specific employee, newest-first.
Parameters
employeeId ID of the employee whose takeout history is requested.
Returns
Non-null list; empty when the employee has no recorded takeouts.
Definition at line 152 of file ResourceTakeLogStore.java.
References getAll().
log()
synchronized void log (Long employeeId, String employeeName, String employeeRole, Long resourceId, String resourceName, Long storageId, int quantity)
Prepends a new takeout entry to the log file.
Prepending (index 0) keeps the file ordered newest-first without sorting on every write.
Parameters
employeeId ID of the employee who took the resource.
employeeName Display name of the employee.
employeeRole Role class name (e.g., "Technician").
resourceId Catalogue ID of the resource that was taken.
resourceName Display name of the resource.
storageId ID of the storage facility the resource was taken from.
quantity Number of units taken.
Exceptions
RuntimeException When the updated list cannot be written to disk.
Definition at line 176 of file ResourceTakeLogStore.java.
References getAll().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/resources/ResourceTakeLogStore.java