VIX Health System: JsonAuditLogRepository Class Reference
JsonAuditLogRepository Class Reference
Append-only JSON-file-backed repository for AuditLog entries.
Public Member Functions
JsonAuditLogRepository ()
Configures the mapper and ensures the backing file exists on disk.
List< AuditLog > findAll ()
Returns all audit log entries in insertion order (NFR02 — read-only access).
synchronized AuditLog save (AuditLog log)
Appends a new log entry, assigning a sequential ID if absent (NFR02).
List< AuditLog > findByEntityType (String entityType)
Finds all log entries for a given entity type.
List< AuditLog > findByUsername (String username)
Finds all log entries recorded under a specific username.
List< AuditLog > findByAction (String action)
Finds all log entries whose action field contains the given keyword.
List< AuditLog > findRecent (int limit)
Returns the most recent log entries sorted by timestamp descending.
Detailed Description
Append-only JSON-file-backed repository for AuditLog entries.
Persists audit logs to src/main/resources/storage/audit-logs.json. Intentionally exposes no delete or update methods to enforce NFR02 (Traceability) — once written, a log entry is immutable for normal users. The save(AuditLog) method is synchronized to prevent ID collisions under concurrent request handling.
See also
com.nvivx.vixhealthsystem.model.AuditLog
Definition at line 27 of file JsonAuditLogRepository.java.
Constructor & Destructor Documentation
JsonAuditLogRepository()
JsonAuditLogRepository ()
Configures the mapper and ensures the backing file exists on disk.
Creates an empty JSON array file if audit-logs.json is missing so that subsequent reads never fail with a file-not-found error.
Definition at line 49 of file JsonAuditLogRepository.java.
Member Function Documentation
findAll()
List< AuditLog > findAll ()
Returns all audit log entries in insertion order (NFR02 — read-only access).
Returns
all log entries; never null, empty list if file is empty
Exceptions
RuntimeException if the file cannot be parsed
Definition at line 87 of file JsonAuditLogRepository.java.
Referenced by findByAction(), findByEntityType(), findByUsername(), findRecent(), and save().
save()
synchronized AuditLog save (AuditLog log)
Appends a new log entry, assigning a sequential ID if absent (NFR02).
Synchronised to prevent duplicate IDs under concurrent writes. Existing entries are never modified.
Parameters
log the entry to append; must not be null
Returns
the same entry with its ID populated
Exceptions
RuntimeException if the file cannot be written
Definition at line 113 of file JsonAuditLogRepository.java.
References findAll().
findByEntityType()
List< AuditLog > findByEntityType (String entityType)
Finds all log entries for a given entity type.
Parameters
entityType case-sensitive entity name (e.g. "Employee", "Patient")
Returns
matching entries; empty list if none found
Definition at line 143 of file JsonAuditLogRepository.java.
References findAll().
findByUsername()
List< AuditLog > findByUsername (String username)
Finds all log entries recorded under a specific username.
Parameters
username the actor's username as stored in the log entries
Returns
matching entries; empty list if none found
Definition at line 155 of file JsonAuditLogRepository.java.
References findAll().
findByAction()
List< AuditLog > findByAction (String action)
Finds all log entries whose action field contains the given keyword.
Parameters
action action keyword (e.g. "CREATE", "UPDATE", "DELETE")
Returns
matching entries; empty list if none found
Definition at line 167 of file JsonAuditLogRepository.java.
References findAll().
findRecent()
List< AuditLog > findRecent (int limit)
Returns the most recent log entries sorted by timestamp descending.
Parameters
limit maximum number of entries to return; must be positive
Returns
up to limit most recent entries
Definition at line 179 of file JsonAuditLogRepository.java.
References findAll().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/repository/JsonAuditLogRepository.java