VIX Health System: DepartmentService Class Reference
DepartmentService Class Reference
Manages hospital departments and their associated specialists.
Public Member Functions
DepartmentService (DepartmentRepository departmentRepository, EmployeeRepository employeeRepository)
Constructs the service with its required repositories.
List< Department > getAllDepartments ()
Returns every department persisted in the database.
Department getDepartmentById (Long id)
Looks up a department by its numeric primary key.
Department getDepartmentById (String id)
String-typed overload for controller convenience; delegates to getDepartmentById(Long) after parsing.
List< MedicalSpecialist > getDoctorsByDepartment (Long departmentId)
Returns all MedicalSpecialist employees assigned to the given department.
List< MedicalSpecialist > getDoctorsByDepartment (String departmentId)
String-typed overload for controller convenience; delegates to getDoctorsByDepartment(Long) after parsing.
Map< Long, String > getAllDoctorImageMap ()
Builds a stable specialistId → image-path map for every specialist across all departments using only two database queries (all departments + all employees).
Map< Long, String > getDoctorImageMap (Long departmentId)
Builds a stable specialistId → image-path map for a single department.
List< String > getServicesByDepartment (Long departmentId)
Returns the catalogue of clinical services offered by the given department.
List< String > getServicesByDepartment (String departmentId)
String-typed overload; tries numeric parse first, falls back to name-based lookup when the value is a slug (e.g., "cardiology" from a URL path).
Detailed Description
Manages hospital departments and their associated specialists.
Covers department listing, doctor lookup, and department-service catalogue queries.
Not annotated @Transactional(readOnly=true) at the class level because most operations are already read-only and the service performs no writes; individual write paths can opt in if added in the future.
See also
EmployeeService
vixhealthsystem.model.facility.Department
vixhealthsystem.model.person.employee.MedicalSpecialist
Definition at line 26 of file DepartmentService.java.
Constructor & Destructor Documentation
DepartmentService()
DepartmentService (DepartmentRepository departmentRepository, EmployeeRepository employeeRepository)
Constructs the service with its required repositories.
Parameters
departmentRepository Provides persistence access to Department entities.
employeeRepository Required for filtering specialists by department in-memory, since JPA inheritance prevents a direct typed query.
Definition at line 46 of file DepartmentService.java.
Member Function Documentation
getAllDepartments()
List< Department > getAllDepartments ()
Returns every department persisted in the database.
Returns
Non-null list; empty when no departments exist.
Definition at line 61 of file DepartmentService.java.
getDepartmentById() [1/2]
Department getDepartmentById (Long id)
Looks up a department by its numeric primary key.
Parameters
id Database ID of the department.
Returns
The matching Department, or null if not found.
Definition at line 71 of file DepartmentService.java.
Referenced by getDepartmentById(), getDoctorImageMap(), and getServicesByDepartment().
getDepartmentById() [2/2]
Department getDepartmentById (String id)
String-typed overload for controller convenience; delegates to getDepartmentById(Long) after parsing.
Parameters
id String representation of the department's numeric ID.
Returns
The matching Department, or null when the ID is non-numeric or does not exist.
Definition at line 83 of file DepartmentService.java.
References getDepartmentById().
getDoctorsByDepartment() [1/2]
List< MedicalSpecialist > getDoctorsByDepartment (Long departmentId)
Returns all MedicalSpecialist employees assigned to the given department.
Filters in-memory after loading all employees because the single-table-inheritance mapping does not allow a typed repository query for subtypes.
Parameters
departmentId ID of the target department.
Returns
Non-null list of specialists; empty if none are assigned.
Definition at line 105 of file DepartmentService.java.
Referenced by getDoctorImageMap(), and getDoctorsByDepartment().
getDoctorsByDepartment() [2/2]
List< MedicalSpecialist > getDoctorsByDepartment (String departmentId)
String-typed overload for controller convenience; delegates to getDoctorsByDepartment(Long) after parsing.
Parameters
departmentId String representation of the department ID.
Returns
Non-null list; empty when the ID is non-numeric or has no specialists.
Definition at line 121 of file DepartmentService.java.
References getDoctorsByDepartment().
getAllDoctorImageMap()
Map< Long, String > getAllDoctorImageMap ()
Builds a stable specialistId → image-path map for every specialist across all departments using only two database queries (all departments + all employees).
Male and female counters reset per department; the image pool wraps at index 2 to avoid null paths when there are more than two doctors of the same gender.
Returns
LinkedHashMap ordered by department iteration order; never null.
Definition at line 143 of file DepartmentService.java.
getDoctorImageMap()
Map< Long, String > getDoctorImageMap (Long departmentId)
Builds a stable specialistId → image-path map for a single department.
Doctors are sorted by ID so that adding or removing staff never reshuffles existing photo assignments. The counter wraps at 2 per gender to stay within the available static asset set.
Parameters
departmentId ID of the department to map.
Returns
Ordered map of specialist ID to image path; empty map when the department does not exist.
Definition at line 181 of file DepartmentService.java.
References getDepartmentById(), and getDoctorsByDepartment().
getServicesByDepartment() [1/2]
List< String > getServicesByDepartment (Long departmentId)
Returns the catalogue of clinical services offered by the given department.
Services are resolved from the department name because no DepartmentServices table exists yet. Known departments: Cardiology, Neurology, Radiology, Administration.
Parameters
departmentId ID of the target department.
Returns
Non-null list of service descriptions; empty when the department is not found.
See also
#getServicesByDepartmentName(String)
Definition at line 216 of file DepartmentService.java.
References getDepartmentById().
Referenced by getServicesByDepartment().
getServicesByDepartment() [2/2]
List< String > getServicesByDepartment (String departmentId)
String-typed overload; tries numeric parse first, falls back to name-based lookup when the value is a slug (e.g., "cardiology" from a URL path).
Parameters
departmentId Numeric ID or department name string.
Returns
Non-null list of service descriptions.
Definition at line 231 of file DepartmentService.java.
References getServicesByDepartment().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/core/DepartmentService.java