VIX Health System: MockSpidController Class Reference
MockSpidController Class Reference
Simulates SPID and CIE government-identity login pages for demo purposes.
Public Member Functions
String spidLogin ()
GET /mock-spid/login — render the mock SPID login form.
String spidAuthenticate (@RequestParam String fiscalCode, @RequestParam String pin, Model model)
POST /mock-spid/authenticate — validate the fiscal code and PIN, then redirect to the SPID callback.
String cieLogin ()
GET /mock-cie/login — render the mock CIE login form.
String cieAuthenticate (@RequestParam String fiscalCode, @RequestParam String pin, Model model)
POST /mock-cie/authenticate — validate the fiscal code and PIN, then redirect to the CIE callback.
Detailed Description
Simulates SPID and CIE government-identity login pages for demo purposes.
In a production deployment these endpoints would be replaced by redirects to the real Italian government identity providers (SPID and CIE). Here they host simplified mock login pages that accept a patient's fiscal code as the "assertion token", perform minimal validation, and then hand off to the real patient auth callback in PatientAuthController.
Auth flow: /patient/login → /mock-spid/login → POST /mock-spid/authenticate → redirect /patient/spid-callback?fiscalCode=... → /mock-cie/login → POST /mock-cie/authenticate → redirect /patient/cie-callback?fiscalCode=...
These endpoints are public (no authentication required) because they are the entry point to the login flow.
See also
PatientAuthController
PatientService
Definition at line 30 of file MockSpidController.java.
Member Function Documentation
spidLogin()
String spidLogin ()
GET /mock-spid/login — render the mock SPID login form.
Returns
Thymeleaf template mock-spid/login.
Definition at line 48 of file MockSpidController.java.
References spidLogin().
Referenced by spidLogin().
spidAuthenticate()
String spidAuthenticate (@RequestParam String fiscalCode, @RequestParam String pin, Model model)
POST /mock-spid/authenticate — validate the fiscal code and PIN, then redirect to the SPID callback.
Checks that the fiscal code is exactly 16 characters, the PIN is at least 6 digits long, and the patient exists in the database. On success the fiscal code is passed as a query parameter to the patient auth callback, where it acts as the identity assertion token.
Parameters
fiscalCode Italian fiscal code (codice fiscale); trimmed and uppercased.
pin Numeric PIN; must be at least 6 digits.
model Receives an error attribute on validation failure.
Returns
Redirect to /patient/spid-callback?fiscalCode=... on success, or the mock-spid/login template with an error message.
Definition at line 67 of file MockSpidController.java.
References spidAuthenticate().
Referenced by spidAuthenticate().
cieLogin()
String cieLogin ()
GET /mock-cie/login — render the mock CIE login form.
Returns
Thymeleaf template mock-cie/login.
Definition at line 100 of file MockSpidController.java.
References cieLogin().
Referenced by cieLogin().
cieAuthenticate()
String cieAuthenticate (@RequestParam String fiscalCode, @RequestParam String pin, Model model)
POST /mock-cie/authenticate — validate the fiscal code and PIN, then redirect to the CIE callback.
Follows the same validation rules as the SPID flow but without a PIN length check (CIE uses a different credential scheme in production).
Parameters
fiscalCode Italian fiscal code; trimmed and uppercased.
pin PIN value; currently only presence is validated for CIE.
model Receives an error attribute on validation failure.
Returns
Redirect to /patient/cie-callback?fiscalCode=... on success, or the mock-cie/login template with an error message.
Definition at line 117 of file MockSpidController.java.
References cieAuthenticate().
Referenced by cieAuthenticate().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/patient/MockSpidController.java