VIX Health System: EmployeeService Class Reference
EmployeeService Class Reference
Central service for employee lifecycle management — creation, lookup, update, deletion, and Firebase account synchronisation.
Public Member Functions
EmployeeService (EmployeeRepository employeeRepository, DepartmentRepository departmentRepository, AuditService auditService, FirebaseAuthService firebaseAuthService, DevCredentialStore devCredentialStore)
Constructs the service with all required collaborators.
List< Department > findAllDepartments ()
Returns all departments; used to populate department selectors in forms.
Department findDepartmentById (Long id)
Looks up a department by ID, throwing when absent.
Employee findById (Long id)
Looks up an employee by primary key, throwing when absent.
Optional< Employee > findByIdOptional (Long id)
Non-throwing alternative to findById(Long) for callers that handle absence.
List< Employee > findAllEmployees ()
Returns all employees across all roles and departments.
Employee findByEmail (String email)
Finds an employee by their login email address.
Employee findByFirebaseUid (String firebaseUid)
Resolves an employee from their Firebase UID, used during authentication.
List< Employee > findBySurname (String surname)
Returns all employees with the given surname.
List< Employee > findByDepartmentId (Long departmentId)
Returns all employees assigned to the specified department.
List< Employee > findByRole (Class<? extends Employee > employeeType)
Returns all employees that are instances of the given subtype.
List< MedicalSpecialist > findAllMedicalSpecialists ()
Returns all MedicalSpecialist employees in the system.
List< Secretary > findAllSecretaries ()
Returns all Secretary employees in the system.
List< Technician > findAllTechnicians ()
Returns all Technician employees in the system.
List< Buyer > findAllBuyers ()
Returns all Buyer employees in the system.
List< StaffManager > findAllStaffManagers ()
Returns all StaffManager employees in the system.
long getTotalEmployeeCount ()
Returns the total number of employee records (all roles).
long getActiveEmployeeCount ()
Returns the count of active employees.
Employee createEmployee (Employee employee)
Creates a new employee record and a corresponding Firebase Authentication account.
Employee updateEmployee (Long id, Employee updatedData)
Applies a partial update to an existing employee, ignoring null fields.
void requestEmployeePasswordReset (Long employeeId)
Generates a Firebase password-reset link for the employee and logs it to console.
void changeDepartment (Long id, Long newDepartmentId)
Logs a department-change request for the given employee.
void deleteEmployee (Long id)
Deletes an employee from both the database and Firebase Authentication.
Detailed Description
Central service for employee lifecycle management — creation, lookup, update, deletion, and Firebase account synchronisation.
Annotated @Transactional(readOnly=true) at the class level so that all read operations benefit from connection-pool optimisations. Individual write operations override with @Transactional.
Every mutating action is recorded via AuditService to satisfy NFR02 (traceability). Firebase accounts are provisioned alongside the database record so that employees can log in immediately after creation.
See also
FirebaseAuthService
AuditService
DevCredentialStore
com.nvivx.vixhealthsystem.model.person.employee.Employee
Definition at line 43 of file EmployeeService.java.
Constructor & Destructor Documentation
EmployeeService()
EmployeeService (EmployeeRepository employeeRepository, DepartmentRepository departmentRepository, AuditService auditService, FirebaseAuthService firebaseAuthService, DevCredentialStore devCredentialStore)
Constructs the service with all required collaborators.
Parameters
employeeRepository Persistence layer for Employee entities.
departmentRepository Needed to validate and resolve department assignments.
auditService Records every mutating action for traceability (NFR02).
firebaseAuthService Provisions and removes Firebase Authentication accounts.
devCredentialStore DEV-ONLY: persists temporary passwords for the demo board.
Definition at line 72 of file EmployeeService.java.
Member Function Documentation
findDepartmentById()
Department findDepartmentById (Long id)
Looks up a department by ID, throwing when absent.
Parameters
id Department primary key.
Returns
The matching Department; never null.
Exceptions
RuntimeException When no department with the given ID exists.
Definition at line 102 of file EmployeeService.java.
findById()
Employee findById (Long id)
Looks up an employee by primary key, throwing when absent.
Parameters
id Employee primary key.
Returns
The matching Employee; never null.
Exceptions
RuntimeException When no employee with the given ID exists.
Definition at line 118 of file EmployeeService.java.
Referenced by changeDepartment(), deleteEmployee(), requestEmployeePasswordReset(), and updateEmployee().
findByIdOptional()
Optional< Employee > findByIdOptional (Long id)
Non-throwing alternative to findById(Long) for callers that handle absence.
Parameters
id Employee primary key.
Returns
Optional containing the employee, or empty if absent.
Definition at line 129 of file EmployeeService.java.
findByEmail()
Employee findByEmail (String email)
Finds an employee by their login email address.
Parameters
email The employee's email; must be unique in the system.
Returns
The matching employee, or null if not found.
Definition at line 144 of file EmployeeService.java.
findByFirebaseUid()
Employee findByFirebaseUid (String firebaseUid)
Resolves an employee from their Firebase UID, used during authentication.
Parameters
firebaseUid The UID issued by Firebase Authentication after login.
Returns
The matching employee, or null if not found.
Definition at line 154 of file EmployeeService.java.
findBySurname()
List< Employee > findBySurname (String surname)
Returns all employees with the given surname.
Parameters
surname Exact surname match (case-sensitivity is repository-dependent).
Returns
Non-null list; empty if none found.
Definition at line 164 of file EmployeeService.java.
findByDepartmentId()
List< Employee > findByDepartmentId (Long departmentId)
Returns all employees assigned to the specified department.
Parameters
departmentId Primary key of the target department.
Returns
Non-null list; empty if the department has no employees.
Definition at line 174 of file EmployeeService.java.
findByRole()
List< Employee > findByRole (Class<? extends Employee > employeeType)
Returns all employees that are instances of the given subtype.
Used as a generic alternative to the typed findAll* helpers below when the caller already holds a Class token.
Parameters
employeeType Concrete employee subclass (e.g., MedicalSpecialist.class).
Returns
Non-null list of employees that pass the instanceof check.
Definition at line 187 of file EmployeeService.java.
getActiveEmployeeCount()
long getActiveEmployeeCount ()
Returns the count of active employees.
Currently equivalent to total count because no soft-delete / status flag is implemented; retained as a named method so callers need not change when an active/inactive distinction is introduced.
Definition at line 245 of file EmployeeService.java.
createEmployee()
Employee createEmployee (Employee employee)
Creates a new employee record and a corresponding Firebase Authentication account.
A temporary password (ChangeMe123!) is issued and stored in DevCredentialStore for demo visibility. The Firebase UID is written back to the entity before persisting.
Parameters
employee Transient employee entity with at least email set.
Returns
The persisted Employee with a generated ID and Firebase UID.
Exceptions
RuntimeException When the employee has no email or the Firebase API call fails.
Definition at line 264 of file EmployeeService.java.
updateEmployee()
Employee updateEmployee (Long id, Employee updatedData)
Applies a partial update to an existing employee, ignoring null fields.
Only non-null fields in updatedData overwrite the persisted values, making it safe to call with sparse payloads (e.g., updating only a phone number).
Parameters
id ID of the employee to update.
updatedData Carrier object; null fields are ignored.
Returns
The updated and re-persisted Employee.
Exceptions
RuntimeException When no employee with id exists.
Definition at line 322 of file EmployeeService.java.
References findById().
requestEmployeePasswordReset()
void requestEmployeePasswordReset (Long employeeId)
Generates a Firebase password-reset link for the employee and logs it to console.
The link is also recorded in DevCredentialStore so it is not lost between demo page refreshes. The employee's email must be set for this to succeed.
Parameters
employeeId ID of the employee whose password should be reset.
Exceptions
RuntimeException When the employee has no email or the Firebase API call fails.
Definition at line 356 of file EmployeeService.java.
References findById().
changeDepartment()
void changeDepartment (Long id, Long newDepartmentId)
Logs a department-change request for the given employee.
The actual department field is not updated here; this method records the intent in the audit log and is intended as a placeholder for a future approval workflow.
Parameters
id ID of the employee requesting the change.
newDepartmentId ID of the target department.
Exceptions
RuntimeException When no employee with id exists.
Definition at line 401 of file EmployeeService.java.
References findById().
deleteEmployee()
void deleteEmployee (Long id)
Deletes an employee from both the database and Firebase Authentication.
The Firebase account is removed first; if that fails the database record is not deleted to avoid orphaned auth entries. The dev credential entry is cleaned up regardless of Firebase success to keep the demo board tidy.
Parameters
id ID of the employee to delete.
Exceptions
RuntimeException When no employee exists with id, or when the Firebase deletion fails.
Definition at line 424 of file EmployeeService.java.
References findById().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/core/EmployeeService.java