VIX Health System: DevCredentialStore Class Reference
DevCredentialStore Class Reference
DEV-ONLY store that keeps plaintext employee credentials visible on the demo login board.
Classes
class Entry
One credential entry per employee; serialised as a flat JSON object.
Public Member Functions
DevCredentialStore ()
Initialises the Jackson mapper with Java-time support and ensures the backing JSON file exists on disk.
synchronized List< Entry > getAll ()
Returns all stored credential entries, or an empty list if the file is missing.
synchronized void store (String email, String name, String role, String password)
Adds or replaces the credential entry for the given email.
synchronized void updatePassword (String email, String newPassword)
Updates the stored password for an existing entry and clears the reset flag.
synchronized void markResetTriggered (String email)
Marks that a Firebase password-reset link was sent for this employee.
synchronized void remove (String email)
Removes the credential entry for the given email, if it exists.
Detailed Description
DEV-ONLY store that keeps plaintext employee credentials visible on the demo login board.
Because Firebase does not expose passwords after creation, newly created employee accounts would otherwise be unrecoverable in a demo environment without a password-reset email. This store solves that by holding the temporary password (ChangeMe123!) alongside the employee's name and role so the staff manager demo page can display it.
Credentials are written to dev-credentials.json and are never used for actual authentication — all auth goes through Firebase. Do NOT include this service in any production build.
All public methods are synchronized to prevent concurrent read/write corruption from multi-threaded request handling.
See also
com.nvivx.vixhealthsystem.service.core.EmployeeService
Definition at line 32 of file DevCredentialStore.java.
Member Function Documentation
store()
synchronized void store (String email, String name, String role, String password)
Adds or replaces the credential entry for the given email.
If an entry already exists for the email (e.g., from a previous create attempt), it is removed before the new one is inserted.
Parameters
email Employee login email (used as the unique key).
name Display name for the demo board.
role Employee subtype name.
password Plaintext temporary password.
Definition at line 142 of file DevCredentialStore.java.
References getAll().
updatePassword()
synchronized void updatePassword (String email, String newPassword)
Updates the stored password for an existing entry and clears the reset flag.
Parameters
email Email identifying the entry to update.
newPassword The new plaintext password.
Definition at line 155 of file DevCredentialStore.java.
References getAll().
remove()
synchronized void remove (String email)
Removes the credential entry for the given email, if it exists.
Called during employee deletion so the demo board stays clean.
Parameters
email Email identifying the entry to remove.
Definition at line 186 of file DevCredentialStore.java.
References getAll().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/DevCredentialStore.java