VIX Health System: InventoryService Class Reference
InventoryService Class Reference
Manages hospital resource inventory — stock levels across all storage facilities, low-stock detection, and resource intake/consumption flows.
Classes
class ResourceWithQuantity
View-model wrapper that pairs a Resource with its current stock level and low-stock flag, used by Thymeleaf inventory templates.
Public Member Functions
InventoryService (ResourceRepository resourceRepository, StorageRepository storageRepository, AuditService auditService, ResourceTakeLogStore takeLogStore)
Constructs the service with all required repositories and collaborators.
List< Resource > getAllResources ()
Returns all resource catalogue entries in the system.
Resource getResourceById (Long id)
Looks up a resource by its catalogue ID, throwing when absent.
List< Resource > searchResourcesByName (String name)
Finds resources whose name contains the given substring (case-insensitive).
Resource createResource (String name, String description, BigDecimal price)
Adds a new resource to the catalogue with zero initial stock.
Resource updateResource (Long id, String name, String description, BigDecimal price)
Updates catalogue metadata for an existing resource; null parameters are ignored.
void deleteResource (Long id)
Removes a resource from the catalogue.
Map< Resource, Integer > getStorageInventory (Long storageId)
Returns the stock map for a specific storage facility.
Map< Resource, Integer > getTotalInventory ()
Aggregates stock quantities across all storage facilities (FR7.2).
List< ResourceWithQuantity > getLowStockResources ()
Returns all resources whose total stock across all facilities falls below DEFAULT_LOW_STOCK_THRESHOLD (FR5.5 — inventory alerts).
void addResourceToStorage (Buyer buyer, Long resourceId, int quantity)
Add quantity to a resource in storage via a buyer (UC27).
void addResourceToStorage (Long storageId, Long resourceId, int quantity)
Overload kept for internal/system use where no specific buyer actor is present.
void removeResourceFromStorage (Employee employee, Long resourceId, int quantity)
Remove quantity from a resource in storage via an employee (UC25).
void removeResourceFromStorage (Long storageId, Long resourceId, int quantity)
Overload kept for internal/system use where no specific employee actor is present.
boolean isResourceLowStock (Long resourceId)
Checks whether a specific resource is below the low-stock threshold across all facilities.
int getTotalResourceQuantity (Long resourceId)
Returns the total quantity of a resource summed across all storage facilities.
Detailed Description
Manages hospital resource inventory — stock levels across all storage facilities, low-stock detection, and resource intake/consumption flows.
Covers FR5.5 (inventory visibility) and UC25 (employee resource consumption) and UC27 (buyer restocking).
Annotated @Transactional(readOnly=true) at the class level; write methods override with @Transactional.
Two actor-aware overloads exist for stock mutations: the domain-method path (accepts an Employee or Buyer actor) enforces business rules inside the model, while the ID-only overloads are provided for internal/system use when no actor is in scope.
See also
ResourceTakeLogStore
com.nvivx.vixhealthsystem.model.resource.Storage
AuditService
Definition at line 39 of file InventoryService.java.
Constructor & Destructor Documentation
InventoryService()
InventoryService (ResourceRepository resourceRepository, StorageRepository storageRepository, AuditService auditService, ResourceTakeLogStore takeLogStore)
Constructs the service with all required repositories and collaborators.
Parameters
resourceRepository Persistence layer for Resource catalogue entries.
storageRepository Persistence layer for Storage facilities and their stock maps.
auditService Records every stock mutation for traceability (NFR02).
takeLogStore JSON-backed log of every resource takeout event (FR5.5).
Definition at line 65 of file InventoryService.java.
Member Function Documentation
getAllResources()
List< Resource > getAllResources ()
Returns all resource catalogue entries in the system.
Returns
Non-null list; empty when no resources have been defined.
Definition at line 84 of file InventoryService.java.
getResourceById()
Resource getResourceById (Long id)
Looks up a resource by its catalogue ID, throwing when absent.
Parameters
id Resource primary key.
Returns
The matching Resource; never null.
Exceptions
RuntimeException When no resource with the given ID exists.
Definition at line 95 of file InventoryService.java.
Referenced by addResourceToStorage(), addResourceToStorage(), deleteResource(), removeResourceFromStorage(), removeResourceFromStorage(), and updateResource().
searchResourcesByName()
List< Resource > searchResourcesByName (String name)
Finds resources whose name contains the given substring (case-insensitive).
Parameters
name Search term.
Returns
Non-null list of matching resources.
Definition at line 106 of file InventoryService.java.
createResource()
Resource createResource (String name, String description, BigDecimal price)
Adds a new resource to the catalogue with zero initial stock.
Parameters
name Display name of the resource.
description Optional description; may be null.
price Unit purchase price in euros.
Returns
The persisted Resource with a generated ID.
Definition at line 123 of file InventoryService.java.
updateResource()
Resource updateResource (Long id, String name, String description, BigDecimal price)
Updates catalogue metadata for an existing resource; null parameters are ignored.
Parameters
id ID of the resource to update.
name New display name; null keeps the existing value.
description New description; null keeps the existing value.
price New unit price; null keeps the existing value.
Returns
The updated and re-persisted Resource.
Exceptions
RuntimeException When no resource with id exists.
Definition at line 144 of file InventoryService.java.
References getResourceById().
deleteResource()
void deleteResource (Long id)
Removes a resource from the catalogue.
Storage-usage validation is not yet enforced; callers should check usage before calling this method to avoid orphaned storage-resource references.
Parameters
id ID of the resource to delete.
Exceptions
RuntimeException When no resource with id exists.
Definition at line 169 of file InventoryService.java.
References getResourceById().
getStorageInventory()
Map< Resource, Integer > getStorageInventory (Long storageId)
Returns the stock map for a specific storage facility.
Re-fetches fully-loaded Resource objects from the repository so that the returned map contains rich entities rather than JPA proxy stubs from the @ElementCollection.
Parameters
storageId ID of the storage facility.
Returns
Map of Resource to quantity; never null.
Exceptions
RuntimeException When no storage with storageId exists.
Definition at line 197 of file InventoryService.java.
getTotalInventory()
Map< Resource, Integer > getTotalInventory ()
Aggregates stock quantities across all storage facilities (FR7.2).
Iterates all Storage entities and merges their resource maps by summing quantities for the same resource. @ElementCollection(EAGER) means each storage's map is loaded in one additional query.
Returns
Map of Resource to total quantity across all storages; never null.
Definition at line 223 of file InventoryService.java.
Referenced by getLowStockResources(), getTotalResourceQuantity(), and isResourceLowStock().
getLowStockResources()
List< ResourceWithQuantity > getLowStockResources ()
Returns all resources whose total stock across all facilities falls below DEFAULT_LOW_STOCK_THRESHOLD (FR5.5 — inventory alerts).
Returns
Non-null list of ResourceWithQuantity wrappers; empty when all resources are adequately stocked.
Definition at line 240 of file InventoryService.java.
References getTotalInventory().
addResourceToStorage()
void addResourceToStorage (Buyer buyer, Long resourceId, int quantity)
Add quantity to a resource in storage via a buyer (UC27).
Uses the Buyer domain method, which delegates to Storage domain logic.
Definition at line 259 of file InventoryService.java.
References Buyer.addResource(), and getResourceById().
removeResourceFromStorage()
void removeResourceFromStorage (Employee employee, Long resourceId, int quantity)
Remove quantity from a resource in storage via an employee (UC25).
Uses the Employee domain method, which delegates to Storage domain logic.
Definition at line 299 of file InventoryService.java.
References getResourceById(), and Employee.takeResource().
isResourceLowStock()
boolean isResourceLowStock (Long resourceId)
Checks whether a specific resource is below the low-stock threshold across all facilities.
Parameters
resourceId Catalogue ID of the resource to check.
Returns
true when the aggregated quantity is below DEFAULT_LOW_STOCK_THRESHOLD.
Definition at line 354 of file InventoryService.java.
References getTotalInventory().
getTotalResourceQuantity()
int getTotalResourceQuantity (Long resourceId)
Returns the total quantity of a resource summed across all storage facilities.
Parameters
resourceId Catalogue ID of the resource.
Returns
Total stock; 0 when the resource is not stocked anywhere.
Definition at line 368 of file InventoryService.java.
References getTotalInventory().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/resources/InventoryService.java