VIX Health System: PaymentController Class Reference
PaymentController Class Reference
Controller for the payment workflow — base URL /payment.
Public Member Functions
String showPaymentPage (@PathVariable int appointmentId, Model model)
GET /payment/appointment/{appointmentId} — render the payment form for an appointment.
PaymentStatus getPaymentStatus (@PathVariable String paymentId)
GET /payment/status/{paymentId} — fetch the current status of a payment transaction.
String paymentConfirmation (@PathVariable int appointmentId, Model model)
GET /payment/confirmation/{appointmentId} — render the post-payment confirmation page.
PaymentResponse processPayment (@RequestBody PaymentRequest request)
POST /payment/process — process a card payment via the payment service.
String fakePayment (@RequestParam int appointmentId, @RequestParam float amount, RedirectAttributes redirectAttributes)
POST /payment/fake-pay — simulate a successful payment for demo purposes.
Detailed Description
Controller for the payment workflow — base URL /payment.
Manages the end-to-end payment flow for appointment fees: showing the payment form, processing a real card payment via PaymentService, querying transaction status, and a fake-pay shortcut for demo/test purposes that simulates a successful transaction without real card data. After a successful payment the appointment status is set to CONFIRMED.
See also
PaymentService
JsonAppointmentRepository
Definition at line 27 of file PaymentController.java.
Member Function Documentation
showPaymentPage()
String showPaymentPage (@PathVariable int appointmentId, Model model)
GET /payment/appointment/{appointmentId} — render the payment form for an appointment.
Looks up the appointment to confirm it exists before presenting the payment form; redirects back to the appointments list if it does not.
Parameters
appointmentId Numeric ID of the appointment to pay for.
model Receives appointmentId, amount, and pageTitle.
Returns
Thymeleaf template payment/payment-form, or redirect to /patient/appointments?error=... when the appointment is not found.
Definition at line 55 of file PaymentController.java.
References showPaymentPage().
Referenced by showPaymentPage().
getPaymentStatus()
PaymentStatus getPaymentStatus (@PathVariable String paymentId)
GET /payment/status/{paymentId} — fetch the current status of a payment transaction.
Parameters
paymentId Transaction identifier returned by the payment gateway.
Returns
PaymentStatus JSON body with status and any message.
Definition at line 76 of file PaymentController.java.
paymentConfirmation()
String paymentConfirmation (@PathVariable int appointmentId, Model model)
GET /payment/confirmation/{appointmentId} — render the post-payment confirmation page.
Parameters
appointmentId Numeric ID of the appointment that was just paid.
model Receives appointmentId, appointment, and pageTitle.
Returns
Thymeleaf template payment/confirmation.
Definition at line 88 of file PaymentController.java.
References paymentConfirmation().
Referenced by paymentConfirmation().
processPayment()
PaymentResponse processPayment (@RequestBody PaymentRequest request)
POST /payment/process — process a card payment via the payment service.
Accepts a full PaymentRequest (card number, CVV, expiry, amount) and delegates to PaymentService#processPayment. Returns the gateway response as JSON; the caller is responsible for acting on the status field.
Parameters
request JSON body containing payment and appointment details.
Returns
PaymentResponse JSON body with status, transaction ID, and any error message.
Definition at line 114 of file PaymentController.java.
fakePayment()
String fakePayment (@RequestParam int appointmentId, @RequestParam float amount, RedirectAttributes redirectAttributes)
POST /payment/fake-pay — simulate a successful payment for demo purposes.
Builds a hard-coded PaymentRequest with a test card number and calls the real payment service path so that the same confirmation and status-update logic runs as in a live transaction. On success the appointment is marked as paid and CONFIRMED before redirecting.
Parameters
appointmentId Numeric ID of the appointment to mark as paid.
amount Amount to simulate; shown in the success flash message.
redirectAttributes Flash attributes carrying a success message or an error back to the confirmation page.
Returns
Redirect to /payment/confirmation/{appointmentId}.
Definition at line 133 of file PaymentController.java.
References fakePayment().
Referenced by fakePayment().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/services/PaymentController.java