VIX Health System: Secretary Class Reference
Secretary Class Reference
Handles administrative tasks such as appointment scheduling, patient admissions and discharges.
Public Member Functions
Secretary ()
Default constructor required by JPA.
Role getSystemRole ()
Returns the system authentication role for this employee type.
EmployeeType getEmployeeType ()
Returns the employee type enum identifying this employee's role in the organisation.
Appointment makeAppointmentForPatient (Patient p, MedicalSpecialist m, LocalDateTime dt)
Books an appointment for a patient with a specific specialist on behalf of the patient.
void rescheduleAppointmentForPatient (Patient p, LocalDateTime dtOld, LocalDateTime dtNew)
Reschedules an existing appointment to a new date on behalf of a patient.
void cancelAppointmentForPatient (Patient p, LocalDateTime dt)
Cancels an appointment on behalf of a patient.
void setPatientInRoom (InternationRoom ir, Patient p) throws Exception
Assigns a patient to an inpatient room.
void dismissPatient (InternationRoom ir, Patient p) throws Exception
Discharges a patient from an inpatient room.
Public Member Functions inherited from Employee
boolean hasFacilityStorage ()
Takes a quantity of a resource from the facility storage, navigating through the employee's own department → facility → storage chain.
Storage getFacilityStorage ()
Returns the storage unit belonging to this employee's facility.
String getFacilityName ()
Returns the name of the medical facility this employee belongs to.
void takeResource (Resource r, int q) throws Exception
Withdraws a quantity of a resource from this employee's facility storage.
Public Member Functions inherited from Person
Person ()
Default constructor required by JPA.
Person (String name, String surname, LocalDate birthDate, String birthPlace, char gender, String email, String phoneNumber)
Creates a Person with the specified personal and contact information.
int getAge ()
Calculates the current age based on the date of birth.
Detailed Description
Handles administrative tasks such as appointment scheduling, patient admissions and discharges.
The secretary role identifies the secretary's specialization:
Front Office
Admissions
Billing
See also
Employee
Definition at line 29 of file Secretary.java.
Member Function Documentation
makeAppointmentForPatient()
Appointment makeAppointmentForPatient (Patient p, MedicalSpecialist m, LocalDateTime dt)
Books an appointment for a patient with a specific specialist on behalf of the patient.
Delegates to the patient's own appointment-creation logic.
Parameters
p the patient
m the medical specialist
dt the appointment date and time
Returns
the newly created appointment
Definition at line 92 of file Secretary.java.
References Patient.makeAppointment().
Referenced by AppointmentService.bookForSecretary().
rescheduleAppointmentForPatient()
void rescheduleAppointmentForPatient (Patient p, LocalDateTime dtOld, LocalDateTime dtNew)
Reschedules an existing appointment to a new date on behalf of a patient.
Delegates to the patient's own reschedule logic.
Parameters
p the patient
dtOld the current appointment date and time
dtNew the new appointment date and time
Definition at line 108 of file Secretary.java.
References Patient.rescheduleAppointment().
cancelAppointmentForPatient()
void cancelAppointmentForPatient (Patient p, LocalDateTime dt)
Cancels an appointment on behalf of a patient.
Delegates to the patient's own cancellation logic.
Parameters
p the patient
dt the appointment date and time to cancel
Definition at line 123 of file Secretary.java.
References Patient.cancelAppointment().
setPatientInRoom()
void setPatientInRoom (InternationRoom ir, Patient p) throws Exception
Assigns a patient to an inpatient room.
Delegates to the room's own admission logic.
Parameters
ir the inpatient room to assign the patient to
p the patient to assign
Exceptions
Exception if the room is full
Definition at line 142 of file Secretary.java.
Referenced by RoomService.admitPatient().
dismissPatient()
void dismissPatient (InternationRoom ir, Patient p) throws Exception
Discharges a patient from an inpatient room.
Delegates to the room's own removal logic.
Parameters
ir the inpatient room the patient is currently in
p the patient to discharge
Exceptions
Exception if the patient is not in the room
Definition at line 157 of file Secretary.java.
Referenced by RoomService.dismissPatient().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/person/employee/Secretary.java