VIX Health System: PatientService Class Reference
PatientService Class Reference
Manages the patient lifecycle : registration, lookup, partial updates, and GDPR-compliant account deletion.
Public Member Functions
PatientService (PatientRepository patientRepository, AuditService auditService)
Constructs the service with its required collaborators.
Patient findById (long id)
Looks up a patient by primary key, throwing when absent.
Optional< Patient > findByFiscalCode (String fiscalCode)
Looks up a patient by their national fiscal code.
List< Patient > findAllPatients ()
Returns all patients in the system.
List< Patient > searchPatients (String query)
Searches patients by name, surname, or fiscal code using case-insensitive substring matching.
Patient createPatient (Patient patient)
Persists a new patient and writes an audit entry.
Patient updatePatient (long id, Patient updatedData)
Applies a partial update to an existing patient, ignoring null fields.
void deletePatient (long id)
Anonymises a patient account while preserving all clinical records (GDPR soft-delete).
void permanentDeletePatient (long id)
Permanently deletes a patient and ALL associated medical records from the database.
Detailed Description
Manages the patient lifecycle : registration, lookup, partial updates, and GDPR-compliant account deletion.
Annotated @Transactional(readOnly=true) at the class level so that all read operations benefit from connection-pool optimisations; write methods override with @Transactional.
Deletion follows a two-tier model: deletePatient(long) anonymises personal data while preserving clinical records (NFR04 + NFR09), whereas permanentDeletePatient(long) cascades all data and should only be used for legal erasure requests.
See also
vixhealthsystem.model.person.Patient
MedicalRecordService
AuditService
Definition at line 32 of file PatientService.java.
Constructor & Destructor Documentation
PatientService()
PatientService (PatientRepository patientRepository, AuditService auditService)
Constructs the service with its required collaborators.
Parameters
patientRepository Persistence layer for Patient entities.
auditService Records every mutating action (NFR02 : traceability).
Definition at line 51 of file PatientService.java.
Member Function Documentation
findById()
Patient findById (long id)
Looks up a patient by primary key, throwing when absent.
Parameters
id Patient primary key.
Returns
The matching Patient; never null.
Exceptions
RuntimeException When no patient with the given ID exists.
Definition at line 67 of file PatientService.java.
Referenced by deletePatient(), permanentDeletePatient(), and updatePatient().
findByFiscalCode()
Optional< Patient > findByFiscalCode (String fiscalCode)
Looks up a patient by their national fiscal code.
Parameters
fiscalCode The patient's unique fiscal/tax code.
Returns
Optional containing the patient, or empty if absent.
Definition at line 78 of file PatientService.java.
searchPatients()
List< Patient > searchPatients (String query)
Searches patients by name, surname, or fiscal code using case-insensitive substring matching.
Filtering is performed in-memory because the repository does not yet expose a compound search query. A blank query returns all patients.
Parameters
query Search term; null or blank returns all patients.
Returns
Non-null list of matching patients.
Definition at line 97 of file PatientService.java.
References findAllPatients().
createPatient()
Patient createPatient (Patient patient)
Persists a new patient and writes an audit entry.
Parameters
patient Transient patient entity to persist.
Returns
The saved Patient with a generated ID.
Definition at line 124 of file PatientService.java.
updatePatient()
Patient updatePatient (long id, Patient updatedData)
Applies a partial update to an existing patient, ignoring null fields.
Parameters
id ID of the patient to update.
updatedData Carrier object with the fields to overwrite; null fields are skipped.
Returns
The updated and re-persisted Patient.
Exceptions
RuntimeException When no patient with id exists.
Definition at line 140 of file PatientService.java.
References findById(), and Patient.updateProfile().
deletePatient()
void deletePatient (long id)
Anonymises a patient account while preserving all clinical records (GDPR soft-delete).
Personal identifiers (name, surname, email, phone) are overwritten or nulled. The fiscal code is replaced with a timestamped tombstone token so the row remains uniquely identifiable internally. Medical conditions, prescriptions, and surgeries are intentionally kept to satisfy the 5-year clinical retention requirement (NFR09).
Prefer this method over permanentDeletePatient(long) for all normal deletion requests.
Deletes (anonymizes) a patient account while preserving medical records.
GDPR Compliance (NFR04):
Personal data (name, surname, email, phone) is removed
Fiscal code is replaced with a unique DELETED_ timestamp
Medical records (conditions, prescriptions, surgeries) are preserved for clinical and legal requirements (NFR09 - 5-year retention)
Definition at line 176 of file PatientService.java.
References Patient.deleteAccount(), findById(), and Patient.setFiscalCode().
permanentDeletePatient()
void permanentDeletePatient (long id)
Permanently deletes a patient and ALL associated medical records from the database.
This is a destructive, non-recoverable operation intended only for testing environments or court-ordered erasure when anonymisation is legally insufficient. In all other cases, use deletePatient(long) instead.
Parameters
id ID of the patient to permanently erase.
Exceptions
RuntimeException When no patient with the given ID exists.
Definition at line 219 of file PatientService.java.
References findById().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/core/PatientService.java