VIX Health System: StaffManagerController Class Reference
StaffManagerController Class Reference
Controller for StaffManager users — base URL /staff-manager.
Public Member Functions
String dashboard (Model model)
GET /staff-manager/dashboard — render the staff manager's overview dashboard.
String listEmployees (@RequestParam(required=false) String type, Model model)
GET /staff-manager/employees — list all employees, optionally filtered by type.
String showCreateEmployeeForm (Model model)
GET /staff-manager/employees/create — render the create-employee form.
String createEmployee (@RequestParam String name, @RequestParam String surname, @RequestParam String email, @RequestParam String employeeType, @RequestParam(required=false) String specialty, @RequestParam(required=false) String licenseNumber, @RequestParam(required=false) Long departmentId, @RequestParam(required=false) String hireDate, @RequestParam(required=false) String gender, @RequestParam(required=false) String phone, @RequestParam(required=false) String birthDate, @RequestParam(required=false) String birthPlace, HttpSession session, Model model)
POST /staff-manager/employees/create — create a new employee account.
String resetEmployeePassword (@RequestParam Long employeeId, HttpSession session, Model model)
POST /staff-manager/employees/reset-password — trigger a Firebase password-reset email.
String deleteEmployee (@RequestParam Long employeeId, HttpSession session, Model model)
POST /staff-manager/employees/delete — permanently delete an employee account.
String manageShifts (Model model)
GET /staff-manager/shifts — display all shifts with a form to assign new ones.
String assignShift (@RequestParam Long employeeId, @RequestParam String date, @RequestParam String shiftType, Model model)
POST /staff-manager/shifts/assign — assign a shift to an employee on a specific date.
String manageVacations (Model model)
GET /staff-manager/vacations — display all vacation requests with approve/deny controls.
String addVacationRequest (@RequestParam Long employeeId, @RequestParam String startDate, @RequestParam String endDate, @RequestParam(required=false) String reason, Model model)
POST /staff-manager/vacations/add — submit a new vacation request for an employee.
String approveVacation (@RequestParam int requestId, Model model)
POST /staff-manager/vacations/approve — approve a pending vacation request.
String denyVacation (@RequestParam int requestId, Model model)
POST /staff-manager/vacations/deny — deny a pending vacation request.
String viewAvailability (Model model)
GET /staff-manager/availability — show a cross-referenced availability overview.
String viewAuditLogs (@RequestParam(required=false) String entityType, Model model)
GET /staff-manager/audit-logs — display system-wide audit log entries.
String viewProfile (HttpSession session, Model model)
GET /staff-manager/profile — display the staff manager's personal profile page.
String viewResourceLog (Model model)
GET /staff-manager/resource-log — display the global resource-take audit log.
String viewEmployeeDetail (@PathVariable Long id, Model model, HttpSession session)
GET /staff-manager/employees/{id} — display a detailed view of a single employee.
Detailed Description
Controller for StaffManager users — base URL /staff-manager.
Staff managers administer the entire workforce of VIX Health System. This controller covers employee lifecycle management (create, delete, password reset), shift assignment with vacation-conflict detection, vacation request approval/denial, an availability overview that cross-references shifts and appointments, system-wide audit-log browsing, and the manager's own profile view.
Only accessible to users with ROLE_STAFFMANAGER.
Use cases covered: UC01–UC05 (staff management), UC06 (shifts), UC07 (vacations), UC08 (availability), UC09 (audit logs).
See also
EmployeeService
ShiftService
VacationService
AuditService
Definition at line 53 of file StaffManagerController.java.
Member Function Documentation
dashboard()
String dashboard (Model model)
GET /staff-manager/dashboard — render the staff manager's overview dashboard.
Parameters
model Receives totalEmployees, activeEmployees, pendingVacations, and recentActivities (last 10 audit entries).
Returns
Thymeleaf template staff-manager/dashboard.
Definition at line 88 of file StaffManagerController.java.
References dashboard().
Referenced by dashboard().
listEmployees()
String listEmployees (@RequestParam(required=false) String type, Model model)
GET /staff-manager/employees — list all employees, optionally filtered by type.
Parameters
type Optional filter string: one of MEDICAL_SPECIALIST, SECRETARY, TECHNICIAN, BUYER, STAFF_MANAGER; all employees are returned when absent.
model Receives employees, employeeTypes, and selectedType.
Returns
Thymeleaf template staff-manager/employees.
Definition at line 112 of file StaffManagerController.java.
References listEmployees().
Referenced by listEmployees().
showCreateEmployeeForm()
String showCreateEmployeeForm (Model model)
GET /staff-manager/employees/create — render the create-employee form.
Parameters
model Receives employeeTypes and departments for form dropdowns.
Returns
Thymeleaf template staff-manager/create-employee.
Definition at line 157 of file StaffManagerController.java.
References showCreateEmployeeForm().
Referenced by showCreateEmployeeForm().
createEmployee()
String createEmployee (@RequestParam String name, @RequestParam String surname, @RequestParam String email, @RequestParam String employeeType, @RequestParam(required=false) String specialty, @RequestParam(required=false) String licenseNumber, @RequestParam(required=false) Long departmentId, @RequestParam(required=false) String hireDate, @RequestParam(required=false) String gender, @RequestParam(required=false) String phone, @RequestParam(required=false) String birthDate, @RequestParam(required=false) String birthPlace, HttpSession session, Model model)
POST /staff-manager/employees/create — create a new employee account.
Builds the correct Employee subtype from the employeeType parameter, then calls the domain method StaffManager.createAccountForEmployee for business-rule validation before persisting. The acting StaffManager is resolved from the session.
Parameters
name First name of the new employee.
surname Last name of the new employee.
email Work email address (used for Firebase login later).
employeeType One of MEDICAL_SPECIALIST, SECRETARY, TECHNICIAN, BUYER, STAFF_MANAGER.
specialty Specialty string; only relevant for MedicalSpecialist.
licenseNumber Medical licence number; only relevant for MedicalSpecialist.
departmentId Optional department to assign the employee to.
hireDate ISO date string (yyyy-MM-dd); defaults to today.
gender Single character 'M' or 'F'; optional.
phone Phone number; optional.
birthDate ISO date string; optional.
birthPlace City of birth; optional.
session HTTP session; used to resolve the StaffManager domain object.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 191 of file StaffManagerController.java.
References StaffManager.createAccountForEmployee(), and createEmployee().
Referenced by createEmployee().
resetEmployeePassword()
String resetEmployeePassword (@RequestParam Long employeeId, HttpSession session, Model model)
POST /staff-manager/employees/reset-password — trigger a Firebase password-reset email.
Calls the domain method StaffManager.credentialsRecovery for business-rule validation before delegating to EmployeeService#requestEmployeePasswordReset.
Parameters
employeeId Database ID of the employee whose password is to be reset.
session HTTP session; used to resolve the StaffManager domain object.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 278 of file StaffManagerController.java.
References StaffManager.credentialsRecovery(), and resetEmployeePassword().
Referenced by resetEmployeePassword().
deleteEmployee()
String deleteEmployee (@RequestParam Long employeeId, HttpSession session, Model model)
POST /staff-manager/employees/delete — permanently delete an employee account.
Calls StaffManager.deleteEmployeeAccount first; that domain method enforces the rule that a manager cannot delete their own account.
Parameters
employeeId Database ID of the employee to delete.
session HTTP session; used to resolve the StaffManager domain object.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 316 of file StaffManagerController.java.
References deleteEmployee(), and StaffManager.deleteEmployeeAccount().
Referenced by deleteEmployee().
manageShifts()
String manageShifts (Model model)
GET /staff-manager/shifts — display all shifts with a form to assign new ones.
Parameters
model Receives employees and shifts attributes.
Returns
Thymeleaf template staff-manager/shifts.
Definition at line 348 of file StaffManagerController.java.
References manageShifts().
Referenced by manageShifts().
assignShift()
String assignShift (@RequestParam Long employeeId, @RequestParam String date, @RequestParam String shiftType, Model model)
POST /staff-manager/shifts/assign — assign a shift to an employee on a specific date.
Rejects the assignment with an error message when the employee has an approved vacation that overlaps with date.
Parameters
employeeId Database ID of the employee.
date ISO date string (yyyy-MM-dd) for the shift day.
shiftType Shift type identifier (e.g., "MORNING", "AFTERNOON", "NIGHT").
model Receives a success or conflict/error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 369 of file StaffManagerController.java.
References assignShift().
Referenced by assignShift().
manageVacations()
String manageVacations (Model model)
GET /staff-manager/vacations — display all vacation requests with approve/deny controls.
Parameters
model Receives pendingRequests, allRequests, and employees.
Returns
Thymeleaf template staff-manager/vacations.
Definition at line 409 of file StaffManagerController.java.
References manageVacations().
Referenced by manageVacations().
addVacationRequest()
String addVacationRequest (@RequestParam Long employeeId, @RequestParam String startDate, @RequestParam String endDate, @RequestParam(required=false) String reason, Model model)
POST /staff-manager/vacations/add — submit a new vacation request for an employee.
Parameters
employeeId Database ID of the employee.
startDate ISO date string (yyyy-MM-dd) for the first day of leave.
endDate ISO date string (yyyy-MM-dd) for the last day of leave.
reason Optional reason for the request; defaults to empty string.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 429 of file StaffManagerController.java.
References addVacationRequest().
Referenced by addVacationRequest().
approveVacation()
String approveVacation (@RequestParam int requestId, Model model)
POST /staff-manager/vacations/approve — approve a pending vacation request.
Parameters
requestId Numeric ID of the vacation request to approve.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 459 of file StaffManagerController.java.
References approveVacation().
Referenced by approveVacation().
denyVacation()
String denyVacation (@RequestParam int requestId, Model model)
POST /staff-manager/vacations/deny — deny a pending vacation request.
Parameters
requestId Numeric ID of the vacation request to deny.
model Receives a success or error message attribute.
Returns
Thymeleaf template staff-manager/result.
Definition at line 480 of file StaffManagerController.java.
References denyVacation().
Referenced by denyVacation().
viewAvailability()
String viewAvailability (Model model)
GET /staff-manager/availability — show a cross-referenced availability overview.
Builds maps of shifts, approved vacations, and upcoming appointments (for MedicalSpecialists) keyed by employee ID so the template can render each person's schedule at a glance.
Parameters
model Receives employees, shiftsByEmployee, vacationsByEmployee, and appointmentsBySpecialist.
Returns
Thymeleaf template staff-manager/availability.
Definition at line 509 of file StaffManagerController.java.
References viewAvailability().
Referenced by viewAvailability().
viewAuditLogs()
String viewAuditLogs (@RequestParam(required=false) String entityType, Model model)
GET /staff-manager/audit-logs — display system-wide audit log entries.
All entries are shown sorted newest-first. An optional entity-type filter narrows the list to a single domain object category.
Parameters
entityType Optional filter (e.g., "Appointment", "Patient"); all entries are shown when absent.
model Receives logs, entityTypes (distinct sorted list), and selectedEntityType.
Returns
Thymeleaf template staff-manager/audit-logs.
Definition at line 598 of file StaffManagerController.java.
References viewAuditLogs().
Referenced by viewAuditLogs().
viewProfile()
String viewProfile (HttpSession session, Model model)
GET /staff-manager/profile — display the staff manager's personal profile page.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives employee, roleLabel, dashboardLink, and isSpecialist=false.
Returns
Thymeleaf template employee/profile, or redirect:/login when no session user is found.
Definition at line 631 of file StaffManagerController.java.
References viewProfile().
Referenced by viewProfile().
viewResourceLog()
String viewResourceLog (Model model)
GET /staff-manager/resource-log — display the global resource-take audit log.
Parameters
model Receives logs (all entries from ResourceTakeLogStore).
Returns
Thymeleaf template staff-manager/resource-log.
Definition at line 658 of file StaffManagerController.java.
References viewResourceLog().
Referenced by viewResourceLog().
viewEmployeeDetail()
String viewEmployeeDetail (@PathVariable Long id, Model model, HttpSession session)
GET /staff-manager/employees/{id} — display a detailed view of a single employee.
Shows the employee's shifts, approved vacations, and (for MedicalSpecialists) their upcoming non-cancelled appointments.
Parameters
id Database ID of the employee to display.
model Receives employee, shifts, vacations, appointments (non-empty only for MedicalSpecialists), and roleLabel.
session HTTP session; the session user must be present or a redirect to /login is returned.
Returns
Thymeleaf template staff-manager/employee-detail, or redirect to /staff-manager/employees when the ID is not found.
Definition at line 681 of file StaffManagerController.java.
References viewEmployeeDetail().
Referenced by viewEmployeeDetail().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/StaffManagerController.java