VIX Health System: PatientAuthController Class Reference
PatientAuthController Class Reference
Controller for patient authentication, dashboard, profile, and account management — base URL /patient.
Public Member Functions
String showLoginPage (@RequestParam(required=false) String redirect, Model model)
GET /patient/login — render the patient login page.
String authenticate (@RequestParam String fiscalCode, @RequestParam(required=false) String redirectUrl, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
POST /patient/authenticate — log in a patient using their fiscal code.
String logout (HttpSession session)
GET /patient/logout — invalidate the patient session and redirect to the login page.
String spidCallback (@RequestParam String fiscalCode, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
GET /patient/spid-callback — receive the fiscal code from the mock SPID portal and create a session.
String cieCallback (@RequestParam String fiscalCode, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
GET /patient/cie-callback — receive the fiscal code from the mock CIE portal and create a session.
String dashboard (HttpSession session, Model model)
GET /patient/dashboard — render the patient's personal dashboard.
String profile (HttpSession session, Model model)
GET /patient/profile — display the patient's personal profile.
String records (HttpSession session, Model model)
GET /patient/records — display the patient's medical records.
String deleteAccount (@RequestParam(required=false) String confirm, HttpSession session, Model model)
POST /patient/delete — anonymize and delete the patient's account.
Detailed Description
Controller for patient authentication, dashboard, profile, and account management — base URL /patient.
Patients authenticate using their Italian fiscal code (codice fiscale) either directly through the portal form or via the mock SPID/CIE government-identity flow in MockSpidController. On successful authentication a patient object is stored in the HTTP session and a Spring Security context is registered so that route-level access rules work correctly. Every significant action (login, logout, deletion) is written to the audit log.
See also
MockSpidController
PatientService
AuditService
Definition at line 36 of file PatientAuthController.java.
Member Function Documentation
showLoginPage()
String showLoginPage (@RequestParam(required=false) String redirect, Model model)
GET /patient/login — render the patient login page.
Parameters
redirect Optional relative path to redirect to after a successful login; stored in the model for the login form to forward.
model Receives redirectUrl.
Returns
Thymeleaf template patient/login.
Definition at line 59 of file PatientAuthController.java.
References showLoginPage().
Referenced by showLoginPage().
authenticate()
String authenticate (@RequestParam String fiscalCode, @RequestParam(required=false) String redirectUrl, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
POST /patient/authenticate — log in a patient using their fiscal code.
Looks up the patient by fiscal code, stores the entity in the HTTP session under the "patient" key, registers a Spring Security context so that route guards work, and audits the login event. Redirects to an optional custom URL or to the dashboard by default.
Parameters
fiscalCode Italian fiscal code used as the patient's identity.
redirectUrl Optional relative path (without /patient/) to redirect to after login; defaults to dashboard.
session HTTP session; receives "patient" and "role" attributes.
request Raw servlet request (passed to Spring Security plumbing).
response Raw servlet response (passed to Spring Security plumbing).
model Receives an error attribute on failed login.
Returns
Redirect to the target URL, or patient/login with an error.
Definition at line 82 of file PatientAuthController.java.
References authenticate().
Referenced by authenticate().
logout()
String logout (HttpSession session)
GET /patient/logout — invalidate the patient session and redirect to the login page.
Parameters
session HTTP session to invalidate.
Returns
Redirect to /patient/login.
Definition at line 123 of file PatientAuthController.java.
References logout().
Referenced by logout().
spidCallback()
String spidCallback (@RequestParam String fiscalCode, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
GET /patient/spid-callback — receive the fiscal code from the mock SPID portal and create a session.
The fiscal code is treated as the identity assertion token (in production this would be a signed SAML response). Delegates to createPatientSession which is shared with the CIE flow.
Parameters
fiscalCode Fiscal code passed as a query parameter by the mock SPID portal.
session HTTP session to populate.
request Raw servlet request (retained for future filter hooks).
response Raw servlet response (retained for future filter hooks).
model Receives an error attribute on lookup failure.
Returns
Redirect to /patient/dashboard, or patient/login with an error on failure.
Definition at line 154 of file PatientAuthController.java.
References spidCallback().
Referenced by spidCallback().
cieCallback()
String cieCallback (@RequestParam String fiscalCode, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
GET /patient/cie-callback — receive the fiscal code from the mock CIE portal and create a session.
Identical flow to the SPID callback; both ultimately call createPatientSession.
Parameters
fiscalCode Fiscal code passed by the mock CIE portal.
session HTTP session to populate.
request Raw servlet request (retained for future filter hooks).
response Raw servlet response (retained for future filter hooks).
model Receives an error attribute on lookup failure.
Returns
Redirect to /patient/dashboard, or patient/login with an error on failure.
Definition at line 177 of file PatientAuthController.java.
References cieCallback().
Referenced by cieCallback().
dashboard()
String dashboard (HttpSession session, Model model)
GET /patient/dashboard — render the patient's personal dashboard.
Reloads a fresh Patient entity from the database so that any session staleness does not affect the data displayed (e.g., newly booked appointments added by another session or by a secretary).
Parameters
session HTTP session; must contain a "patient" attribute.
model Receives patient and pageTitle attributes.
Returns
Thymeleaf template patient/dashboard, or redirect:/patient/login when no session patient is found.
Definition at line 202 of file PatientAuthController.java.
References dashboard().
Referenced by dashboard().
profile()
String profile (HttpSession session, Model model)
GET /patient/profile — display the patient's personal profile.
Parameters
session HTTP session; must contain a "patient" attribute.
model Receives patient and pageTitle attributes.
Returns
Thymeleaf template patient/profile, or redirect:/patient/login when no session patient is found.
Definition at line 223 of file PatientAuthController.java.
References profile().
Referenced by profile().
records()
String records (HttpSession session, Model model)
GET /patient/records — display the patient's medical records.
Reloads from the database to ensure that the medical record and its collections (diagnoses, prescriptions, etc.) are attached to an active Hibernate session and load correctly without lazy-loading exceptions.
Parameters
session HTTP session; must contain a "patient" attribute.
model Receives patient and pageTitle attributes.
Returns
Thymeleaf template patient/records, or redirect:/patient/login when no session patient is found.
Definition at line 247 of file PatientAuthController.java.
References records().
Referenced by records().
deleteAccount()
String deleteAccount (@RequestParam(required=false) String confirm, HttpSession session, Model model)
POST /patient/delete — anonymize and delete the patient's account.
Requires the patient to submit the string "CONFIRM" as the confirm parameter; any other value (or an absent value) renders a confirmation page instead. Medical records are retained for five years per GDPR Article 17(3)(c) even though personal identifiers are anonymized.
Parameters
confirm Must equal "CONFIRM" (case-sensitive) to proceed.
session HTTP session; invalidated on successful deletion.
model Receives requireConfirm=true when confirmation is needed, or a message attribute on success.
Returns
Redirect to / on success, the patient/confirm-delete template when confirmation is pending, or redirect:/patient/login when no session patient is found.
Definition at line 281 of file PatientAuthController.java.
References deleteAccount().
Referenced by deleteAccount().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/patient/PatientAuthController.java