VIX Health System: MachineryService Class Reference
MachineryService Class Reference
Manages the lifecycle and status of medical equipment across all hospital facilities.
Classes
class AlertInfo
Lightweight view-model for a faulty-machine alert shown on the technician dashboard.
Public Member Functions
MachineryService (MachineryRepository machineryRepository, AuditService auditService)
Constructs the service with its required collaborators.
List< Machinery > getAllMachines ()
Returns all machinery registered in the hospital network.
Machinery getMachineById (Long id)
Looks up a machine by primary key, throwing when absent.
List< Machinery > getMachinesByStatus (MachineStatus status)
Returns all machines that currently have the given MachineStatus.
List< Machinery > getWorkingMachines ()
Returns all machines with status MachineStatus#WORKING (FR5.3).
List< Machinery > getFaultyMachines ()
Get all faulty machines (UC24, FR5.4 - Machine malfunction alert).
List< Machinery > getFaultyMachinesForTechnician (Technician technician)
Returns all faulty machines as identified by the given technician.
List< Machinery > getMachinesUnderMaintenance ()
Returns all machines currently under scheduled maintenance.
List< Machinery > getMachinesByRoom (Long roomId)
Returns all machines assigned to a specific specialised room.
Machinery updateMachineStatus (Long machineId, MachineStatus newStatus)
Sets a machine's operational status and writes an audit entry (FR5.3).
Machinery reportFaultyMachine (Long machineId, String issueDescription)
Marks a machine as MachineStatus#FAULTY and logs the issue (FR5.4).
Machinery repairMachine (Long machineId)
Marks a machine as MachineStatus#WORKING after repair is complete.
Machinery scheduleMaintenance (Long machineId, String reason)
Transitions a machine to MachineStatus#UNDER_MAINTENANCE status.
long getFaultyMachineCount ()
Returns the number of machines currently in FAULTY status (for dashboard badges).
long getMaintenanceMachineCount ()
Returns the number of machines currently under scheduled maintenance.
long getWorkingMachineCount ()
Returns the number of machines currently in WORKING status.
long getTotalMachineCount ()
Returns the total number of machines registered in the system.
boolean hasFaultyMachines ()
Returns true when at least one machine is currently FAULTY (for alert banners).
List< AlertInfo > getActiveAlerts ()
Returns alert descriptors for all faulty machines, used to populate the technician dashboard alert panel (FR5.4).
Detailed Description
Manages the lifecycle and status of medical equipment across all hospital facilities.
Covers UC24 (machine malfunction reporting), FR5.3 (technician visibility), and FR5.4 (machine malfunction alerts).
Annotated @Transactional(readOnly=true) at the class level; write methods override with @Transactional.
Two paths exist for retrieving faulty machines: the repository query path (getFaultyMachines()) and the domain-method path (getFaultyMachinesForTechnician(Technician)), which applies the Machinery model's own isFaulty() logic and is preferred when the acting technician is known.
See also
vixhealthsystem.model.resource.Machinery
AuditService
Definition at line 33 of file MachineryService.java.
Constructor & Destructor Documentation
MachineryService()
MachineryService (MachineryRepository machineryRepository, AuditService auditService)
Constructs the service with its required collaborators.
Parameters
machineryRepository Persistence layer for Machinery entities.
auditService Records every status change for traceability (NFR02).
Definition at line 52 of file MachineryService.java.
Member Function Documentation
getMachineById()
Machinery getMachineById (Long id)
Looks up a machine by primary key, throwing when absent.
Parameters
id Machine primary key.
Returns
The matching Machinery; never null.
Exceptions
RuntimeException When no machine with the given ID exists.
Definition at line 74 of file MachineryService.java.
Referenced by updateMachineStatus().
getMachinesByStatus()
List< Machinery > getMachinesByStatus (MachineStatus status)
Returns all machines that currently have the given MachineStatus.
Parameters
status Target status to filter on.
Returns
Non-null list of matching machines.
Definition at line 85 of file MachineryService.java.
getFaultyMachines()
List< Machinery > getFaultyMachines ()
Get all faulty machines (UC24, FR5.4 - Machine malfunction alert).
Uses DB query directly for efficiency; see also getFaultyMachinesForTechnician(Technician) for the domain-method path.
Definition at line 99 of file MachineryService.java.
References MachineStatus.FAULTY.
Referenced by getActiveAlerts(), and getFaultyMachineCount().
getFaultyMachinesForTechnician()
List< Machinery > getFaultyMachinesForTechnician (Technician technician)
Returns all faulty machines as identified by the given technician.
Uses the Technician domain method, which filters by each machine's own Machinery#isFaulty() logic. Called from the TechnicianController where the acting technician is known.
Definition at line 109 of file MachineryService.java.
References getAllMachines(), and Technician.getFaultyMachineList().
getMachinesByRoom()
List< Machinery > getMachinesByRoom (Long roomId)
Returns all machines assigned to a specific specialised room.
Parameters
roomId Primary key of the specialised room.
Returns
Non-null list of machines in that room.
Definition at line 125 of file MachineryService.java.
updateMachineStatus()
Machinery updateMachineStatus (Long machineId, MachineStatus newStatus)
Sets a machine's operational status and writes an audit entry (FR5.3).
Also calls Machinery#updateStatus() in case the domain method carries additional side-effects (e.g., clearing maintenance timestamps). Adds an alert note in the audit message when the new status is MachineStatus#FAULTY.
Parameters
machineId ID of the machine to update.
newStatus The target MachineStatus.
Returns
The updated and re-persisted Machinery.
Exceptions
RuntimeException When no machine with machineId exists.
Definition at line 146 of file MachineryService.java.
References MachineStatus.FAULTY, getMachineById(), and Machinery.updateStatus().
Referenced by repairMachine(), reportFaultyMachine(), and scheduleMaintenance().
reportFaultyMachine()
Machinery reportFaultyMachine (Long machineId, String issueDescription)
Marks a machine as MachineStatus#FAULTY and logs the issue (FR5.4).
The fault alert becomes visible on the technician dashboard via getActiveAlerts().
Parameters
machineId ID of the machine that is malfunctioning.
issueDescription Free-text description of the observed fault.
Returns
The updated Machinery with FAULTY status.
Exceptions
RuntimeException When no machine with machineId exists.
Definition at line 180 of file MachineryService.java.
References MachineStatus.FAULTY, and updateMachineStatus().
repairMachine()
Machinery repairMachine (Long machineId)
Marks a machine as MachineStatus#WORKING after repair is complete.
Parameters
machineId ID of the repaired machine.
Returns
The updated Machinery with WORKING status.
Exceptions
RuntimeException When no machine with machineId exists.
Definition at line 197 of file MachineryService.java.
References updateMachineStatus(), and MachineStatus.WORKING.
scheduleMaintenance()
Machinery scheduleMaintenance (Long machineId, String reason)
Transitions a machine to MachineStatus#UNDER_MAINTENANCE status.
Parameters
machineId ID of the machine to schedule for maintenance.
reason Reason for the maintenance intervention.
Returns
The updated Machinery with UNDER_MAINTENANCE status.
Exceptions
RuntimeException When no machine with machineId exists.
Definition at line 215 of file MachineryService.java.
References MachineStatus.UNDER_MAINTENANCE, and updateMachineStatus().
getActiveAlerts()
List< AlertInfo > getActiveAlerts ()
Returns alert descriptors for all faulty machines, used to populate the technician dashboard alert panel (FR5.4).
Returns
Non-null list of AlertInfo records; empty when no machines are FAULTY.
Definition at line 257 of file MachineryService.java.
References getFaultyMachines().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/resources/MachineryService.java