VIX Health System: ShiftService Class Reference
ShiftService Class Reference
Manages employee shift assignments, backed by a JSON file rather than the database.
Public Member Functions
ShiftService (AuditService auditService)
Wires up dependencies and ensures the JSON file exists.
List< Shift > getShiftsForEmployee (Long employeeId)
Returns all shifts assigned to a specific employee.
List< Shift > getShiftsForWeek (LocalDate startDate)
Returns all shifts that fall within the 7-day window starting on startDate.
List< Shift > getShiftsForEmployeeBetweenDates (Long employeeId, LocalDate startDate, LocalDate endDate)
Returns an employee's shifts within an inclusive date range.
boolean isEmployeeOnShift (Long employeeId, LocalDate date)
Checks whether an employee is scheduled on a given date.
void assignShift (Long employeeId, LocalDate date, String shiftType)
Assigns a shift to an employee on a given date, replacing any existing shift for that day.
void removeShift (Long shiftId)
Removes a shift by ID.
List< Shift > getAllShifts ()
Returns all shifts in the system, used by the staff manager overview.
Detailed Description
Manages employee shift assignments, backed by a JSON file rather than the database.
Shifts are stored in src/main/resources/storage/shifts.json. The JSON approach was chosen because shift data changes frequently and has no relational dependencies that require foreign-key constraints. Every write is flushed to disk immediately (no caching) so the file always reflects the current state.
The ID sequence is rebuilt from the existing JSON on startup, which means IDs continue incrementing even after a server restart — they are never reused.
All mutating operations are audit-logged via AuditService.
See also
VacationService
vixhealthsystem.model.staff.Shift
Definition at line 35 of file ShiftService.java.
Constructor & Destructor Documentation
ShiftService()
ShiftService (AuditService auditService)
Wires up dependencies and ensures the JSON file exists.
Parameters
auditService Used to record shift assignments and removals.
Definition at line 57 of file ShiftService.java.
Member Function Documentation
getShiftsForEmployee()
List< Shift > getShiftsForEmployee (Long employeeId)
Returns all shifts assigned to a specific employee.
Parameters
employeeId The employee's primary key.
Returns
List of shifts; empty if the employee has none.
Definition at line 122 of file ShiftService.java.
Referenced by isEmployeeOnShift().
getShiftsForWeek()
List< Shift > getShiftsForWeek (LocalDate startDate)
Returns all shifts that fall within the 7-day window starting on startDate.
Parameters
startDate First day of the week (inclusive).
Returns
Shifts across all employees for those 7 days.
Definition at line 134 of file ShiftService.java.
getShiftsForEmployeeBetweenDates()
List< Shift > getShiftsForEmployeeBetweenDates (Long employeeId, LocalDate startDate, LocalDate endDate)
Returns an employee's shifts within an inclusive date range.
Parameters
employeeId The employee's primary key.
startDate Start of the range (inclusive).
endDate End of the range (inclusive).
Returns
Matching shifts; empty list if none found.
Definition at line 149 of file ShiftService.java.
isEmployeeOnShift()
boolean isEmployeeOnShift (Long employeeId, LocalDate date)
Checks whether an employee is scheduled on a given date.
Parameters
employeeId The employee's primary key.
date The date to check.
Returns
true if at least one shift exists for that day.
Definition at line 163 of file ShiftService.java.
References getShiftsForEmployee().
assignShift()
void assignShift (Long employeeId, LocalDate date, String shiftType)
Assigns a shift to an employee on a given date, replacing any existing shift for that day.
Only one shift per employee per day is allowed — if one already exists, it is silently removed before the new one is inserted.
Parameters
employeeId The employee's primary key.
date The date of the shift.
shiftType One of "MORNING", "AFTERNOON", or "NIGHT".
Definition at line 182 of file ShiftService.java.
References Shift.setShiftType().
removeShift()
void removeShift (Long shiftId)
Removes a shift by ID.
Does nothing if the ID doesn't exist.
Parameters
shiftId ID of the shift to delete.
Definition at line 207 of file ShiftService.java.
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/scheduling/ShiftService.java