VIX Health System: Hospital Class Reference
Hospital Class Reference
Represents a hospital.
Public Member Functions
List< InternationRoom > getRoomsForPatients ()
Returns all inpatient rooms available in the hospital.
List< InternationRoom > getFreeRoomsForPatients ()
Returns all inpatient rooms that still have at least one free bed available.
InternationRoom findPatientInRoom (Patient p) throws Exception
Finds the room currently hosting a patient.
void internPatient (Patient p, InternationRoom r) throws Exception
Admits a patient to an inpatient room.
void dismissPatient (Patient p) throws Exception
Discharges a patient from the hospital.
Public Member Functions inherited from MedicalFacility
MedicalFacility ()
Default constructor required by JPA.
MedicalFacility (String name, Location location, String email, String phoneNumber)
Creates a MedicalFacility with the specified details.
Map< Resource, Integer > getResources ()
Returns all resources available in the facility storage.
Detailed Description
Represents a hospital.
A hospital is a medical facility capable of admitting patients for short-term or long-term stays.
Hospitals contain inpatient rooms and provide admission and discharge services.
See also
MedicalFacility
InternationRoom
Patient
Definition at line 24 of file Hospital.java.
Member Function Documentation
getRoomsForPatients()
List< InternationRoom > getRoomsForPatients ()
Returns all inpatient rooms available in the hospital.
An inpatient room is a room designed to accommodate admitted patients for short-term or long-term stays.
The method filters the facility room list and returns only rooms of type InternationRoom.
Returns
list of all inpatient rooms
Definition at line 41 of file Hospital.java.
getFreeRoomsForPatients()
List< InternationRoom > getFreeRoomsForPatients ()
Returns all inpatient rooms that still have at least one free bed available.
Returns
list of available inpatient rooms
Definition at line 57 of file Hospital.java.
References InternationRoom.getNFreeBeds().
findPatientInRoom()
InternationRoom findPatientInRoom (Patient p) throws Exception
Finds the room currently hosting a patient.
Parameters
p the patient to search for
Returns
the patient's room
Exceptions
Exception if the patient is not admitted
Definition at line 75 of file Hospital.java.
References InternationRoom.hasPatient().
Referenced by dismissPatient().
internPatient()
void internPatient (Patient p, InternationRoom r) throws Exception
Admits a patient to an inpatient room.
Parameters
p the patient to admit
r the destination room
Exceptions
Exception if admission fails
Definition at line 95 of file Hospital.java.
dismissPatient()
void dismissPatient (Patient p) throws Exception
Discharges a patient from the hospital.
Parameters
p the patient to discharge
Exceptions
Exception if the patient is not admitted
Definition at line 108 of file Hospital.java.
References findPatientInRoom().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/facility/Hospital.java