VIX Health System: AppointmentService Class Reference
AppointmentService Class Reference
Manages appointment booking, rescheduling, and cancellation for the VIX Health System.
Public Member Functions
AppointmentService (JsonAppointmentRepository repo)
Constructs the service with the JSON-backed appointment repository.
Appointment bookAppointment (CreateAppointmentRequest req)
Books a new appointment from a structured request DTO, checking for slot conflicts.
Appointment bookForSecretary (Secretary secretary, Patient patient, MedicalSpecialist specialist, LocalDateTime dt, int duration, String notes)
Books an appointment on behalf of a patient through a secretary (UC-Secretary flow).
Appointment cancelAppointment (int appointmentId)
Cancels an appointment, delegating cancellability checks to the domain model.
Appointment rescheduleAppointment (int appointmentId, LocalDateTime newDateTime)
Reschedules an active appointment, delegating validity checks to the domain model.
List< Appointment > getAllAppointments ()
Returns all appointments in the system regardless of status.
Detailed Description
Manages appointment booking, rescheduling, and cancellation for the VIX Health System.
Appointments are stored in a JSON file via JsonAppointmentRepository rather than a relational table, so there is no @Transactional support; all reads and writes are synchronized by the repository implementation.
Slot-conflict detection is enforced before every new booking to prevent double-booking across the shared appointment list.
See also
com.nvivx.vixhealthsystem.model.medical.Appointment
com.nvivx.vixhealthsystem.repository.JsonAppointmentRepository
com.nvivx.vixhealthsystem.exception.SlotNotAvailableException
Definition at line 30 of file AppointmentService.java.
Constructor & Destructor Documentation
AppointmentService()
AppointmentService (JsonAppointmentRepository repo)
Constructs the service with the JSON-backed appointment repository.
Parameters
repo File-based repository that reads and writes appointments.json.
Definition at line 47 of file AppointmentService.java.
Member Function Documentation
bookAppointment()
Appointment bookAppointment (CreateAppointmentRequest req)
Books a new appointment from a structured request DTO, checking for slot conflicts.
Parameters
req Appointment details including date-time, duration, and notes.
Returns
The persisted Appointment with a generated ID.
Exceptions
SlotNotAvailableException When the requested time slot overlaps an existing booking.
Definition at line 62 of file AppointmentService.java.
bookForSecretary()
Appointment bookForSecretary (Secretary secretary, Patient patient, MedicalSpecialist specialist, LocalDateTime dt, int duration, String notes)
Books an appointment on behalf of a patient through a secretary (UC-Secretary flow).
Delegates to Secretary#makeAppointmentForPatient so that domain invariants (e.g., patient eligibility) are enforced by the model. The slot-conflict guard runs before the domain call to fail fast.
Parameters
secretary The acting secretary; must not be null.
patient The patient for whom the appointment is being booked.
specialist The medical specialist who will conduct the appointment.
dt Requested date and time for the appointment.
duration Duration in minutes.
notes Optional clinical notes; may be null.
Returns
The persisted Appointment.
Exceptions
SlotNotAvailableException When the slot overlaps an existing booking.
Definition at line 96 of file AppointmentService.java.
References Secretary.makeAppointmentForPatient(), Appointment.setPaymentStatus(), and Appointment.setStatus().
cancelAppointment()
Appointment cancelAppointment (int appointmentId)
Cancels an appointment, delegating cancellability checks to the domain model.
Parameters
appointmentId ID of the appointment to cancel.
Returns
The updated Appointment with canceled status.
Exceptions
RuntimeException When no appointment with appointmentId exists.
Definition at line 126 of file AppointmentService.java.
References Appointment.cancel().
rescheduleAppointment()
Appointment rescheduleAppointment (int appointmentId, LocalDateTime newDateTime)
Reschedules an active appointment, delegating validity checks to the domain model.
Parameters
appointmentId ID of the appointment to reschedule.
newDateTime The new date and time; must be in the future.
Returns
The updated Appointment with the new date-time.
Exceptions
RuntimeException When no appointment with appointmentId exists.
Definition at line 146 of file AppointmentService.java.
References Appointment.reschedule().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/medical/AppointmentService.java