VIX Health System: PatientAppointmentController Class Reference
PatientAppointmentController Class Reference
Controller for patient-side appointment operations — base URL /patient.
Public Member Functions
String viewAppointments (HttpSession session, Model model)
GET /patient/appointments — display the logged-in patient's appointments split into upcoming and past.
String showBookingForm (Model model, HttpSession session)
GET /patient/appointments/book — render the specialist selection step of the booking flow.
String showTimeSlots (@PathVariable Long specialistId, Model model, HttpSession session)
GET /patient/appointments/book/{specialistId} — display available time slots for a specialist.
String bookAppointment (@RequestParam Long specialistId, @RequestParam String dateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/book — save a new appointment for the logged-in patient.
String rescheduleAppointment (@PathVariable int apptId, @RequestParam String newDateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/{apptId}/reschedule — move an existing appointment to a new slot.
String cancelAppointment (@PathVariable int apptId, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/{apptId}/cancel — cancel one of the patient's appointments.
Detailed Description
Controller for patient-side appointment operations — base URL /patient.
Lets authenticated patients view their appointment history, browse available time slots for a given specialist, book a new appointment, reschedule an existing one, and cancel one. Every mutation is written to the audit log via AuditService. All methods verify that the session contains a valid patient object and redirect to the login page when it does not.
See also
PatientAuthController
JsonAppointmentRepository
AuditService
Definition at line 36 of file PatientAppointmentController.java.
Member Function Documentation
viewAppointments()
String viewAppointments (HttpSession session, Model model)
GET /patient/appointments — display the logged-in patient's appointments split into upcoming and past.
Upcoming appointments are those in the future with a status that is neither CANCELLED nor COMPLETED. Past appointments cover everything else, including any future appointment that has been cancelled or marked complete early.
Parameters
session HTTP session; must contain a "patient" attribute.
model Receives upcomingAppointments, pastAppointments, patient, and pageTitle attributes.
Returns
Thymeleaf template patient/appointments, or redirect:/patient/login when no session patient is found.
Definition at line 73 of file PatientAppointmentController.java.
References viewAppointments().
Referenced by viewAppointments().
showBookingForm()
String showBookingForm (Model model, HttpSession session)
GET /patient/appointments/book — render the specialist selection step of the booking flow.
Parameters
model Receives specialists, patient, and pageTitle.
session HTTP session; must contain a "patient" attribute.
Returns
Thymeleaf template patient/book-appointment, or redirect:/patient/login when no session patient is found.
Definition at line 116 of file PatientAppointmentController.java.
References showBookingForm().
Referenced by showBookingForm().
showTimeSlots()
String showTimeSlots (@PathVariable Long specialistId, Model model, HttpSession session)
GET /patient/appointments/book/{specialistId} — display available time slots for a specialist.
Generates hourly slots over the next 14 weekdays (09:00–17:00) and removes any slot already taken by a non-cancelled appointment.
Parameters
specialistId Database ID of the chosen MedicalSpecialist.
model Receives specialist, availableSlots, and patient.
session HTTP session; must contain a "patient" attribute.
Returns
Thymeleaf template patient/select-slot, or a redirect when the specialist is not found or the session is empty.
Definition at line 143 of file PatientAppointmentController.java.
References showTimeSlots().
Referenced by showTimeSlots().
bookAppointment()
String bookAppointment (@RequestParam Long specialistId, @RequestParam String dateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/book — save a new appointment for the logged-in patient.
Uses the domain method Patient.makeAppointment to create the Appointment entity so that model-level invariants are enforced. The slot availability check is re-run here to guard against race conditions since the form was rendered.
Parameters
specialistId Database ID of the chosen MedicalSpecialist.
dateTime Chosen slot in yyyy-MM-ddTHH:mm format.
session HTTP session; must contain a "patient" attribute.
redirectAttributes Flash attributes for the redirect to /patient/appointments.
Returns
Redirect to /patient/appointments.
Definition at line 191 of file PatientAppointmentController.java.
References bookAppointment(), Appointment.setPaymentStatus(), and Appointment.setStatus().
Referenced by bookAppointment().
rescheduleAppointment()
String rescheduleAppointment (@PathVariable int apptId, @RequestParam String newDateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/{apptId}/reschedule — move an existing appointment to a new slot.
Verifies that the appointment belongs to the logged-in patient before delegating to the domain method Appointment.reschedule. The new slot availability is checked before the mutation to prevent double-booking.
Parameters
apptId Numeric ID of the appointment to reschedule.
newDateTime New datetime in yyyy-MM-ddTHH:mm format.
session HTTP session; must contain a "patient" attribute.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /patient/appointments.
Definition at line 253 of file PatientAppointmentController.java.
References Appointment.reschedule(), and rescheduleAppointment().
Referenced by rescheduleAppointment().
cancelAppointment()
String cancelAppointment (@PathVariable int apptId, HttpSession session, RedirectAttributes redirectAttributes)
POST /patient/appointments/{apptId}/cancel — cancel one of the patient's appointments.
Verifies ownership before calling the domain method Appointment.cancel so that a patient cannot cancel another patient's appointment by guessing an ID.
Parameters
apptId Numeric ID of the appointment to cancel.
session HTTP session; must contain a "patient" attribute.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /patient/appointments.
Definition at line 312 of file PatientAppointmentController.java.
References Appointment.cancel(), and cancelAppointment().
Referenced by cancelAppointment().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/patient/PatientAppointmentController.java