VIX Health System: VacationService Class Reference
VacationService Class Reference
Manages employee vacation requests from creation through approval/denial (UC29, FR6.2).
Public Member Functions
VacationService (JsonVacationRepository repository, AuditService auditService)
Constructs the service with the JSON repository and audit collaborator.
VacationRequest addVacationRequest (int employeeId, String employeeName, LocalDate startDate, LocalDate endDate, String reason)
Creates a new vacation request with VacationStatus#PENDING status (UC29).
VacationRequest approveVacation (int id)
Transitions a vacation request to VacationStatus#APPROVED (UC29).
VacationRequest denyVacation (int id)
Transitions a vacation request to VacationStatus#DENIED (UC29).
List< VacationRequest > getAllRequests ()
Returns all vacation requests across all employees and all statuses.
List< VacationRequest > getPendingRequests ()
Returns only requests that are still waiting for a decision.
List< VacationRequest > getRequestsForEmployee (int employeeId)
Returns all requests submitted for a specific employee (any status).
List< VacationRequest > getApprovedRequestsForEmployee (int employeeId)
Returns only the approved requests for a specific employee.
boolean hasOverlappingVacation (int employeeId, LocalDate startDate, LocalDate endDate)
Checks whether an employee has any PENDING or APPROVED request that overlaps the given date range.
long getTotalVacationDaysInYear (int employeeId, int year)
Counts the total approved vacation days taken by an employee in a calendar year.
void deleteRequest (int id)
Removes a vacation request entirely from the JSON store.
Detailed Description
Manages employee vacation requests from creation through approval/denial (UC29, FR6.2).
Requests are stored in vacations.json via JsonVacationRepository rather than the relational database, keeping vacation data separate from the core HR schema. The staff manager is the only actor who can add, approve, deny, or delete requests — employees themselves cannot self-serve vacation through this system.
See also
ShiftService
com.nvivx.vixhealthsystem.model.staff.VacationRequest
AuditService
Definition at line 27 of file VacationService.java.
Constructor & Destructor Documentation
VacationService()
VacationService (JsonVacationRepository repository, AuditService auditService)
Constructs the service with the JSON repository and audit collaborator.
Parameters
repository File-backed repository for VacationRequest entities.
auditService Records every state change for traceability (NFR02).
Definition at line 46 of file VacationService.java.
Member Function Documentation
addVacationRequest()
VacationRequest addVacationRequest (int employeeId, String employeeName, LocalDate startDate, LocalDate endDate, String reason)
Creates a new vacation request with VacationStatus#PENDING status (UC29).
The staff manager calls this on behalf of the employee; the request then waits for approval or denial.
Parameters
employeeId Database ID of the requesting employee.
employeeName Display name used in audit log entries.
startDate First day of the requested vacation period (inclusive).
endDate Last day of the requested vacation period (inclusive).
reason Free-text reason provided by the employee.
Returns
The saved VacationRequest with a generated ID.
Definition at line 68 of file VacationService.java.
References VacationStatus.PENDING.
approveVacation()
VacationRequest approveVacation (int id)
Transitions a vacation request to VacationStatus#APPROVED (UC29).
Parameters
id ID of the request to approve.
Returns
The updated VacationRequest.
Exceptions
com.nvivx.vixhealthsystem.exception.VacationNotFoundException When the ID does not exist.
Definition at line 95 of file VacationService.java.
References VacationStatus.APPROVED, and VacationRequest.setStatus().
denyVacation()
VacationRequest denyVacation (int id)
Transitions a vacation request to VacationStatus#DENIED (UC29).
Parameters
id ID of the request to deny.
Returns
The updated VacationRequest.
Exceptions
com.nvivx.vixhealthsystem.exception.VacationNotFoundException When the ID does not exist.
Definition at line 114 of file VacationService.java.
References VacationStatus.DENIED, and VacationRequest.setStatus().
getRequestsForEmployee()
List< VacationRequest > getRequestsForEmployee (int employeeId)
Returns all requests submitted for a specific employee (any status).
Parameters
employeeId Database ID of the employee.
Returns
Non-null list; empty if the employee has no requests.
Definition at line 148 of file VacationService.java.
Referenced by getTotalVacationDaysInYear(), and hasOverlappingVacation().
getApprovedRequestsForEmployee()
List< VacationRequest > getApprovedRequestsForEmployee (int employeeId)
Returns only the approved requests for a specific employee.
Parameters
employeeId Database ID of the employee.
Returns
Non-null list of approved requests; empty if none found.
Definition at line 160 of file VacationService.java.
References VacationStatus.APPROVED.
hasOverlappingVacation()
boolean hasOverlappingVacation (int employeeId, LocalDate startDate, LocalDate endDate)
Checks whether an employee has any PENDING or APPROVED request that overlaps the given date range.
Used before creating a new request to warn the staff manager about double-booking.
Parameters
employeeId Database ID of the employee.
startDate Start of the proposed period (inclusive).
endDate End of the proposed period (inclusive).
Returns
true if at least one overlapping request exists.
Definition at line 177 of file VacationService.java.
References VacationStatus.APPROVED, getRequestsForEmployee(), and VacationStatus.PENDING.
getTotalVacationDaysInYear()
long getTotalVacationDaysInYear (int employeeId, int year)
Counts the total approved vacation days taken by an employee in a calendar year.
Only approved requests are counted; PENDING and DENIED requests are excluded. The year filter is based on the request's start date.
Parameters
employeeId Database ID of the employee.
year Calendar year to aggregate (e.g., 2025).
Returns
Total number of approved days in that year.
Definition at line 195 of file VacationService.java.
References VacationStatus.APPROVED, VacationRequest.getDaysRequested(), and getRequestsForEmployee().
deleteRequest()
void deleteRequest (int id)
Removes a vacation request entirely from the JSON store.
Parameters
id ID of the request to delete.
Definition at line 212 of file VacationService.java.
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/scheduling/VacationService.java