VIX Health System: MedicalSpecialistController Class Reference
MedicalSpecialistController Class Reference
Controller for MedicalSpecialist staff members — base URL /medical-specialist.
Public Member Functions
String dashboard (Model model)
GET /medical-specialist/dashboard — render the specialist's overview dashboard.
String searchPatientsForm (Model model)
GET /medical-specialist/patients/search — render the patient search form.
String searchPatients (@RequestParam String query, Model model)
POST /medical-specialist/patients/search — execute a patient search and display results.
String viewMedicalRecord (@PathVariable Long patientId, Model model)
GET /medical-specialist/patients/{patientId}/record — view a patient's full medical record.
String addSurgery (@PathVariable Long patientId, @RequestParam String surgeryName, @RequestParam(required=false) String surgeryDescription, @RequestParam String surgeryDateTime, @RequestParam(required=false) Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-surgery — schedule a surgery for a patient.
String addDiagnosis (@PathVariable Long patientId, @RequestParam String diagnosisName, @RequestParam(required=false) String description, @RequestParam String severity, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-diagnosis — add a diagnosis to a patient's record.
String addPrescription (@PathVariable Long patientId, @RequestParam String medication, @RequestParam String dosage, HttpSession session, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-prescription — issue a prescription.
String addExamResult (@PathVariable Long patientId, @RequestParam String examType, @RequestParam String result, @RequestParam(required=false) String notes, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-exam-result — record a diagnostic exam result.
String viewAppointments (HttpSession session, Model model)
GET /medical-specialist/appointments — list all appointments assigned to this specialist.
String viewCalendar (@RequestParam(required=false) String month, HttpSession session, Model model)
GET /medical-specialist/calendar — display a monthly calendar with event markers.
String viewMySchedule (@RequestParam(required=false) String date, HttpSession session, Model model)
GET /medical-specialist/my-schedule — display a day view of shifts, appointments, and surgeries.
String viewProfile (HttpSession session, Model model)
GET /medical-specialist/profile — display the specialist's personal profile.
String viewSurgeries (HttpSession session, Model model)
GET /medical-specialist/surgeries — list all surgeries assigned to this specialist.
Detailed Description
Controller for MedicalSpecialist staff members — base URL /medical-specialist.
Medical specialists use this controller to manage clinical activities: searching patient records, adding diagnoses, prescriptions, exam results, and scheduling surgeries. Additional views cover the specialist's own appointments, a monthly calendar, a day-by-day schedule, and their profile.
Only accessible to users with ROLE_MEDICALSPECIALIST.
Use cases covered: UC10 (view medical records), UC11 (add diagnosis), UC12 (add prescription), UC13 (schedule surgery), UC18 (appointments).
See also
MedicalRecordService
PatientService
ShiftService
VacationService
AuditService
Definition at line 63 of file MedicalSpecialistController.java.
Member Function Documentation
dashboard()
String dashboard (Model model)
GET /medical-specialist/dashboard — render the specialist's overview dashboard.
Parameters
model Receives pageTitle and currentPage attributes.
Returns
Thymeleaf template medical-specialist/dashboard.
Definition at line 106 of file MedicalSpecialistController.java.
References dashboard().
Referenced by dashboard().
searchPatientsForm()
String searchPatientsForm (Model model)
GET /medical-specialist/patients/search — render the patient search form.
Parameters
model Receives pageTitle and currentPage attributes.
Returns
Thymeleaf template medical-specialist/patient-search.
Definition at line 123 of file MedicalSpecialistController.java.
References searchPatientsForm().
Referenced by searchPatientsForm().
searchPatients()
String searchPatients (@RequestParam String query, Model model)
POST /medical-specialist/patients/search — execute a patient search and display results.
Parameters
query Free-text search term (name, fiscal code, etc.).
model Receives patients list and echoes query.
Returns
Thymeleaf template medical-specialist/search-results.
Definition at line 137 of file MedicalSpecialistController.java.
References searchPatients().
Referenced by searchPatients().
viewMedicalRecord()
String viewMedicalRecord (@PathVariable Long patientId, Model model)
GET /medical-specialist/patients/{patientId}/record — view a patient's full medical record.
Also loads the list of specialized operating rooms so the page can offer a room selector when scheduling a new surgery inline.
Parameters
patientId Database ID of the target patient.
model Receives patient, medicalRecord, patientId, and specializedRooms attributes.
Returns
Thymeleaf template medical-specialist/medical-record.
Definition at line 158 of file MedicalSpecialistController.java.
References viewMedicalRecord().
Referenced by viewMedicalRecord().
addSurgery()
String addSurgery (@PathVariable Long patientId, @RequestParam String surgeryName, @RequestParam(required=false) String surgeryDescription, @RequestParam String surgeryDateTime, @RequestParam(required=false) Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-surgery — schedule a surgery for a patient.
The acting specialist is resolved from the session to invoke the domain method MedicalSpecialist.scheduleSurgeryForPatient. The session is consulted rather than the Spring Security principal because only the full MedicalSpecialist domain object carries the scheduling business logic. The operation is audited via AuditService.
Parameters
patientId Database ID of the patient receiving the surgery.
surgeryName Name / type of the surgery.
surgeryDescription Optional narrative description; defaults to empty string.
surgeryDateTime ISO datetime string from an HTML datetime-local input (yyyy-MM-ddTHH:mm or yyyy-MM-ddTHH:mm:ss).
roomId Optional ID of the SpecializedRoom to use.
session HTTP session carrying the "user" Employee attribute.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /medical-specialist/patients/{patientId}/record.
Definition at line 200 of file MedicalSpecialistController.java.
References addSurgery(), and MedicalSpecialist.scheduleSurgeryForPatient().
Referenced by addSurgery().
addDiagnosis()
String addDiagnosis (@PathVariable Long patientId, @RequestParam String diagnosisName, @RequestParam(required=false) String description, @RequestParam String severity, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-diagnosis — add a diagnosis to a patient's record.
Parameters
patientId Database ID of the patient.
diagnosisName Short name of the diagnosis (e.g., "Type 2 Diabetes").
description Optional extended description; defaults to "No description provided".
severity Severity level string (e.g., "LOW", "MEDIUM", "HIGH").
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /medical-specialist/patients/{patientId}/record.
Definition at line 264 of file MedicalSpecialistController.java.
References addDiagnosis().
Referenced by addDiagnosis().
addPrescription()
String addPrescription (@PathVariable Long patientId, @RequestParam String medication, @RequestParam String dosage, HttpSession session, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-prescription — issue a prescription.
The session "user" attribute is read to obtain the specialist's ID, which is stored with the prescription for traceability. Medication and dosage are combined into a single string for the domain service.
Parameters
patientId Database ID of the patient.
medication Medication name.
dosage Dosage instructions (e.g., "500 mg twice daily").
session HTTP session carrying the "user" Employee attribute.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /medical-specialist/patients/{patientId}/record, or redirect:/login when no session user is found.
Definition at line 295 of file MedicalSpecialistController.java.
References addPrescription().
Referenced by addPrescription().
addExamResult()
String addExamResult (@PathVariable Long patientId, @RequestParam String examType, @RequestParam String result, @RequestParam(required=false) String notes, RedirectAttributes redirectAttributes)
POST /medical-specialist/patients/{patientId}/add-exam-result — record a diagnostic exam result.
Parameters
patientId Database ID of the patient.
examType Type of exam (e.g., "Blood Test", "MRI").
result The outcome of the exam.
notes Optional clinical notes; may be null.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /medical-specialist/patients/{patientId}/record.
Definition at line 329 of file MedicalSpecialistController.java.
References addExamResult().
Referenced by addExamResult().
viewAppointments()
String viewAppointments (HttpSession session, Model model)
GET /medical-specialist/appointments — list all appointments assigned to this specialist.
Filters the global appointment repository by the session user's ID and sorts results chronologically. The session "user" attribute is used because appointment filtering requires the specialist's database ID.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives appointments (sorted ascending by date/time).
Returns
Thymeleaf template medical-specialist/appointments.
Definition at line 359 of file MedicalSpecialistController.java.
References viewAppointments().
Referenced by viewAppointments().
viewCalendar()
String viewCalendar (@RequestParam(required=false) String month, HttpSession session, Model model)
GET /medical-specialist/calendar — display a monthly calendar with event markers.
Collects shift dates, appointment dates, surgery dates, and approved vacation ranges for the requested month and passes them to the template as JSON-serialisable string lists so the front-end JavaScript grid can render markers without an additional API call.
Parameters
month Optional yyyy-MM string selecting the displayed month; defaults to the current month when absent or unparseable.
session HTTP session carrying the "user" Employee attribute.
model Receives calYear, calMonth, monthLabel, prevMonth, nextMonth, shiftDates, apptDates, surgeryDates, and vacRanges.
Returns
Thymeleaf template medical-specialist/calendar, or redirect:/login when no session user is found.
Definition at line 397 of file MedicalSpecialistController.java.
References viewCalendar().
Referenced by viewCalendar().
viewMySchedule()
String viewMySchedule (@RequestParam(required=false) String date, HttpSession session, Model model)
GET /medical-specialist/my-schedule — display a day view of shifts, appointments, and surgeries.
Parameters
date Optional ISO date string (yyyy-MM-dd) for the day to display; defaults to today when absent or unparseable.
session HTTP session carrying the "user" Employee attribute.
model Receives selectedDate, selectedDateLabel, prevDate, nextDate, todayShifts, todayAppts, todaySurgeries, and onVacation.
Returns
Thymeleaf template medical-specialist/schedule, or redirect:/login when no session user is found.
Definition at line 473 of file MedicalSpecialistController.java.
References viewMySchedule().
Referenced by viewMySchedule().
viewProfile()
String viewProfile (HttpSession session, Model model)
GET /medical-specialist/profile — display the specialist's personal profile.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives employee, roleLabel, dashboardLink, and isSpecialist=true attributes.
Returns
Thymeleaf template employee/profile, or redirect:/login when no session user is found.
Definition at line 540 of file MedicalSpecialistController.java.
References viewProfile().
Referenced by viewProfile().
viewSurgeries()
String viewSurgeries (HttpSession session, Model model)
GET /medical-specialist/surgeries — list all surgeries assigned to this specialist.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives surgeries (empty list substituted when none exist).
Returns
Thymeleaf template medical-specialist/surgeries, or redirect:/login when no session user is found.
Definition at line 569 of file MedicalSpecialistController.java.
References viewSurgeries().
Referenced by viewSurgeries().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/MedicalSpecialistController.java