VIX Health System: RoomService Class Reference
RoomService Class Reference
Manages patient admission and dismissal across inpatient rooms (UC22 — Triage, UC23 — Patient Dismissal) and provides bed-availability statistics for the dashboard.
Public Member Functions
RoomService (RoomRepository roomRepository, PatientRepository patientRepository, AuditService auditService)
Constructs the service with all required repositories.
List< Room > getAllRooms ()
Returns all rooms of all types in the facility.
Room findById (Long id)
Looks up a room by primary key, throwing when absent.
List< InternationRoom > getAllInpatientRooms ()
Returns only the InternationRoom instances (i.e., rooms that have beds).
List< InternationRoom > getAvailableRooms ()
Get available inpatient rooms (rooms with at least one free bed).
int getTotalAvailableBeds ()
Get total number of available beds across all inpatient rooms.
int getOccupiedBedsCount ()
Get occupied beds count.
int getTotalBeds ()
Get total beds across all inpatient rooms.
void admitPatient (Secretary secretary, Long patientId, Long roomId)
Admit a patient to a room via a secretary (UC22 - Triage).
void dismissPatient (Secretary secretary, Long patientId, Long roomId)
Dismiss a patient from a room via a secretary (UC23 - Patient Dismissal).
InternationRoom findPatientRoom (Long patientId)
Find which room a patient is currently in.
boolean isPatientAdmitted (Long patientId)
Check if a patient is currently admitted.
Detailed Description
Manages patient admission and dismissal across inpatient rooms (UC22 — Triage, UC23 — Patient Dismissal) and provides bed-availability statistics for the dashboard.
Annotated @Transactional(readOnly=true) at the class level; write methods override with @Transactional.
Room polymorphism: the repository stores all Room subtypes; only InternationRoom instances support patient admission. Type-guard checks are applied in admitPatient and dismissPatient to provide clear error messages.
See also
vixhealthsystem.model.facility.InternationRoom
AuditService
Definition at line 32 of file RoomService.java.
Constructor & Destructor Documentation
RoomService()
RoomService (RoomRepository roomRepository, PatientRepository patientRepository, AuditService auditService)
Constructs the service with all required repositories.
Parameters
roomRepository Persistence layer for all Room subtypes.
patientRepository Needed to load patients by ID during admission/dismissal.
auditService Records every bed assignment change (NFR02 — traceability).
Definition at line 53 of file RoomService.java.
Member Function Documentation
findById()
Room findById (Long id)
Looks up a room by primary key, throwing when absent.
Parameters
id Room primary key.
Returns
The matching Room; never null.
Exceptions
RuntimeException When no room with the given ID exists.
Definition at line 77 of file RoomService.java.
Referenced by admitPatient(), and dismissPatient().
admitPatient()
void admitPatient (Secretary secretary, Long patientId, Long roomId)
Admit a patient to a room via a secretary (UC22 - Triage).
Uses the Secretary domain method, which delegates to InternationRoom domain logic.
Definition at line 131 of file RoomService.java.
References findById(), InternationRoom.getNFreeBeds(), and Secretary.setPatientInRoom().
dismissPatient()
void dismissPatient (Secretary secretary, Long patientId, Long roomId)
Dismiss a patient from a room via a secretary (UC23 - Patient Dismissal).
Uses the Secretary domain method, which delegates to InternationRoom domain logic.
Definition at line 164 of file RoomService.java.
References Secretary.dismissPatient(), findById(), and InternationRoom.hasPatient().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/service/resources/RoomService.java