VIX Health System: Employee Class Reference
Employee Class Reference abstract
Represents a generic employee in the system.
Public Member Functions
abstract Role getSystemRole ()
Returns the system authentication role for this employee type.
abstract EmployeeType getEmployeeType ()
Returns the employee type enum identifying this employee's role in the organisation.
boolean hasFacilityStorage ()
Takes a quantity of a resource from the facility storage, navigating through the employee's own department → facility → storage chain.
Storage getFacilityStorage ()
Returns the storage unit belonging to this employee's facility.
String getFacilityName ()
Returns the name of the medical facility this employee belongs to.
void takeResource (Resource r, int q) throws Exception
Withdraws a quantity of a resource from this employee's facility storage.
Public Member Functions inherited from Person
Person ()
Default constructor required by JPA.
Person (String name, String surname, LocalDate birthDate, String birthPlace, char gender, String email, String phoneNumber)
Creates a Person with the specified personal and contact information.
int getAge ()
Calculates the current age based on the date of birth.
Detailed Description
Represents a generic employee in the system.
All specific employee roles inherit from this class. This class is mapped using Single Table Inheritance, meaning that all employee types are stored inside the same Employees table.
The "type" discriminator column is used by JPA to determine which subclass an employee row belongs to.
See also
Buyer
MedicalSpecialist
Secretary
StaffManager
Technician
Definition at line 39 of file Employee.java.
Member Function Documentation
hasFacilityStorage()
boolean hasFacilityStorage ()
Takes a quantity of a resource from the facility storage, navigating through the employee's own department → facility → storage chain.
Parameters
r the resource to take
q the quantity to take
Exceptions
IllegalStateException if department, facility or storage is not set
Exception if the storage has insufficient stock Returns whether this employee has a facility storage they can draw from.
Returns
true when department, facility, and storage are all set.
Definition at line 191 of file Employee.java.
Referenced by AuthController.authenticate(), getFacilityStorage(), AuthController.processLogin(), EmployeeResourceController.takeResource(), and EmployeeResourceController.viewResources().
getFacilityStorage()
Storage getFacilityStorage ()
Returns the storage unit belonging to this employee's facility.
Returns
the facility's Storage
Exceptions
IllegalStateException if department, facility, or storage is not set
Definition at line 204 of file Employee.java.
References hasFacilityStorage().
Referenced by takeResource(), and EmployeeResourceController.viewResources().
getFacilityName()
String getFacilityName ()
Returns the name of the medical facility this employee belongs to.
Returns
facility name, or null if no facility is assigned
Definition at line 216 of file Employee.java.
Referenced by EmployeeResourceController.viewResources().
takeResource()
void takeResource (Resource r, int q) throws Exception
Withdraws a quantity of a resource from this employee's facility storage.
Parameters
r the resource to take
q the quantity to take
Exceptions
IllegalStateException if department, facility or storage is not set
Exception if the storage has insufficient stock
Definition at line 229 of file Employee.java.
References getFacilityStorage().
Referenced by InventoryService.removeResourceFromStorage().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/person/employee/Employee.java