VIX Health System: AuthController Class Reference
AuthController Class Reference
Authentication controller for staff (employees) of VIX Health System.
Public Member Functions
String loginPage (@RequestParam(required=false) String error, Model model)
GET /login — render the staff login form.
String authenticate (@RequestParam String username, @RequestParam String password, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
POST /authenticate — verify Firebase credentials and open a staff session.
String logout (HttpSession session)
GET /logout — invalidate the staff session and clear the security context.
String processLogin (@RequestParam String role, HttpSession session)
POST /select-role — dev-only role selector that bypasses Firebase.
Detailed Description
Authentication controller for staff (employees) of VIX Health System.
Handles login, Firebase-backed credential verification, role-based dashboard redirection, and logout for all employee roles (MedicalSpecialist, Secretary, Technician, Buyer, StaffManager). Also exposes a dev-only role-selector endpoint that bypasses Firebase for local testing.
Base URL: no prefix (login/logout live at the root context).
Use cases covered:
UC01 Staff login via Firebase email/password
Dev quick-login via pre-seeded credential store
See also
FirebaseAuthService
EmployeeService
DevCredentialStore
Definition at line 41 of file AuthController.java.
Member Function Documentation
loginPage()
String loginPage (@RequestParam(required=false) String error, Model model)
GET /login — render the staff login form.
Populates the model with pre-seeded dev credentials so testers can one-click into any role from the login page.
Parameters
error Non-null when Spring Security or a previous authenticate() call redirected here with ?error; triggers an "Invalid credentials" banner.
model Spring MVC model; receives error and devCredentials attributes.
Returns
The login Thymeleaf template.
Definition at line 75 of file AuthController.java.
References loginPage().
Referenced by loginPage().
authenticate()
String authenticate (@RequestParam String username, @RequestParam String password, HttpSession session, HttpServletRequest request, HttpServletResponse response, Model model)
POST /authenticate — verify Firebase credentials and open a staff session.
Calls Firebase to exchange email/password for a UID, looks up the matching Employee, registers a Spring Security context in the HTTP session, then redirects to the role-specific dashboard. Returns to the login page with an error attribute on any failure.
The session attribute "user" stores the Employee entity instead of using the Spring Security principal because employee domain objects carry additional context (department, specialty, etc.) that the principal does not.
Parameters
username Employee's Firebase email address.
password Firebase account password (plain text over HTTPS).
session HTTP session; receives "user" and "role" attributes.
request Raw servlet request (passed to session-security plumbing).
response Raw servlet response (passed to session-security plumbing).
model Receives "error" when authentication fails.
Returns
Redirect to the role-specific dashboard, or the login template with an error message.
Definition at line 105 of file AuthController.java.
References authenticate().
Referenced by authenticate().
logout()
String logout (HttpSession session)
GET /logout — invalidate the staff session and clear the security context.
Parameters
session HTTP session to invalidate.
Returns
Redirect to the public home page /.
Definition at line 166 of file AuthController.java.
References logout().
Referenced by logout().
processLogin()
String processLogin (@RequestParam String role, HttpSession session)
POST /select-role — dev-only role selector that bypasses Firebase.
Looks up the first employee of the requested type from the database, seeds the HTTP session, registers a Spring Security context, then redirects to the matching dashboard. Not intended for production use.
Parameters
role One of: MEDICAL_SPECIALIST, TECHNICIAN, STAFF_MANAGER, SECRETARY, BUYER.
session HTTP session; receives "user" and "role" attributes.
Returns
Redirect to the role-specific dashboard, or redirect:/login when the role string is unrecognized.
Definition at line 191 of file AuthController.java.
References processLogin().
Referenced by processLogin().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/AuthController.java