VIX Health System: Machinery Class Reference
Machinery Class Reference
Represents a medical machine installed inside a specialized room.
Public Member Functions
Machinery ()
Default constructor required by JPA.
Machinery (String name)
Creates a machine with the specified name and initializes its status.
void updateStatus ()
Updates the machine status.
boolean isFaulty ()
Checks whether the machine is faulty.
Detailed Description
Represents a medical machine installed inside a specialized room.
Machines can be operational, under maintenance or faulty. Technicians use the machine status to identify equipment requiring intervention.
See also
SpecializedRoom
MachineStatus
Definition at line 19 of file Machinery.java.
Constructor & Destructor Documentation
Machinery()
Machinery (String name)
Creates a machine with the specified name and initializes its status.
Parameters
name the machine name
Definition at line 63 of file Machinery.java.
References updateStatus().
Member Function Documentation
updateStatus()
void updateStatus ()
Updates the machine status.
Business logic to determine the current status should be implemented here.
Definition at line 170 of file Machinery.java.
References MachineStatus.FAULTY, MachineStatus.UNDER_MAINTENANCE, and MachineStatus.WORKING.
Referenced by Machinery(), and MachineryService.updateMachineStatus().
isFaulty()
boolean isFaulty ()
Checks whether the machine is faulty.
Returns
true if the machine status is FAULTY, false otherwise
Definition at line 186 of file Machinery.java.
References MachineStatus.FAULTY.
Referenced by Technician.getFaultyMachineList().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/resource/Machinery.java