VIX Health System: BuyerController Class Reference
BuyerController Class Reference
Controller for Buyer staff members — base URL /buyer.
Classes
class InventoryItem
Public Member Functions
String dashboard (Model model)
GET /buyer/dashboard — render the buyer's overview dashboard.
String viewInventory (Model model, HttpSession session)
GET /buyer/inventory — list all resources currently in storage.
String viewLowStock (Model model)
GET /buyer/inventory/low-stock — list only resources below the stock threshold.
String showAddResourceForm (Model model)
GET /buyer/inventory/add — render the add-resource form.
String addResource (@RequestParam String name, @RequestParam String description, @RequestParam int quantity, @RequestParam float price, @RequestParam String unit, HttpSession session, Model model)
POST /buyer/inventory/add — create a new resource and add initial stock.
String viewResourceDetails (@PathVariable Long resourceId, Model model)
GET /buyer/inventory/{resourceId} — display details for a single resource.
String updateQuantity (@RequestParam Long resourceId, @RequestParam int quantity, @RequestParam String action, HttpSession session, Model model)
POST /buyer/inventory/update-quantity — add or remove units for an existing resource.
String viewMyShifts (HttpSession session, Model model)
GET /buyer/my-shifts — display the buyer's assigned shifts and approved vacations.
String viewProfile (HttpSession session, Model model)
GET /buyer/profile — display the buyer's personal profile page.
String viewResourceLog (Model model)
GET /buyer/resource-log — show the full resource-take audit log.
Detailed Description
Controller for Buyer staff members — base URL /buyer.
Buyers are responsible for procurement and inventory management. This controller covers the full purchasing workflow: viewing and updating stock levels, adding new resources, monitoring low-stock alerts, reviewing the resource-take audit log, and accessing personal shift and profile pages.
Only accessible to users with ROLE_BUYER.
Use cases covered: UC25 (resource management), UC30 (profile/shifts).
See also
InventoryService
ResourceTakeLogStore
ShiftService
VacationService
Definition at line 41 of file BuyerController.java.
Member Function Documentation
dashboard()
String dashboard (Model model)
GET /buyer/dashboard — render the buyer's overview dashboard.
Populates low-stock count, total resource count, and the buyer's display name (resolved from the first buyer in the database as a temporary measure until session-backed identity is fully wired).
Parameters
model Receives lowStockCount, totalResources, and buyerName attributes.
Returns
Thymeleaf template buyer/dashboard.
Definition at line 77 of file BuyerController.java.
References dashboard().
Referenced by dashboard().
viewInventory()
String viewInventory (Model model, HttpSession session)
GET /buyer/inventory — list all resources currently in storage.
Aggregates stock quantities across all storage locations and wraps each entry in an InventoryItem for the view. Resources with fewer than 50 units are flagged as low-stock. An empty list is substituted and an error banner is shown if the service call fails.
Parameters
model Receives resources (sorted by name), pageTitle, and isLowStockView attributes.
session HTTP session (retained for future session-based filtering).
Returns
Thymeleaf template buyer/inventory.
Definition at line 112 of file BuyerController.java.
References viewInventory().
Referenced by viewInventory().
viewLowStock()
String viewLowStock (Model model)
GET /buyer/inventory/low-stock — list only resources below the stock threshold.
Parameters
model Receives resources (all items flagged as low-stock), pageTitle, and isLowStockView=true.
Returns
Thymeleaf template buyer/inventory.
Definition at line 148 of file BuyerController.java.
References viewLowStock().
Referenced by viewLowStock().
showAddResourceForm()
String showAddResourceForm (Model model)
GET /buyer/inventory/add — render the add-resource form.
Parameters
model Receives pageTitle.
Returns
Thymeleaf template buyer/add-resource.
Definition at line 177 of file BuyerController.java.
References showAddResourceForm().
Referenced by showAddResourceForm().
addResource()
String addResource (@RequestParam String name, @RequestParam String description, @RequestParam int quantity, @RequestParam float price, @RequestParam String unit, HttpSession session, Model model)
POST /buyer/inventory/add — create a new resource and add initial stock.
Creates the resource entity via InventoryService, then calls the domain method Buyer.addResourceToStorage to record the initial quantity. The acting buyer is resolved from the session.
Parameters
name Human-readable resource name.
description Short description of the resource.
quantity Initial quantity to add to storage; must be positive.
price Unit price in euros.
unit Unit of measure label (e.g., "units", "boxes").
session HTTP session; used to resolve the authenticated Buyer via "user" — needed because the Buyer domain object contains the business logic for adding stock.
model Receives a success or error message attribute.
Returns
Thymeleaf template buyer/result.
Definition at line 201 of file BuyerController.java.
References addResource().
Referenced by addResource().
viewResourceDetails()
String viewResourceDetails (@PathVariable Long resourceId, Model model)
GET /buyer/inventory/{resourceId} — display details for a single resource.
Parameters
resourceId Database ID of the resource to display.
model Receives resource, totalQuantity, isLowStock, and lowStockThreshold attributes.
Returns
Thymeleaf template buyer/resource-details, or buyer/result with a not-found message when the ID does not exist.
Definition at line 241 of file BuyerController.java.
References viewResourceDetails().
Referenced by viewResourceDetails().
updateQuantity()
String updateQuantity (@RequestParam Long resourceId, @RequestParam int quantity, @RequestParam String action, HttpSession session, Model model)
POST /buyer/inventory/update-quantity — add or remove units for an existing resource.
Parameters
resourceId ID of the resource whose stock level is being changed.
quantity Number of units to add or remove; must be positive.
action Either "add" or "remove".
session HTTP session; used to resolve the authenticated Buyer (the Buyer domain object owns the storage mutation logic).
model Receives a success or error message attribute.
Returns
Thymeleaf template buyer/result.
Definition at line 273 of file BuyerController.java.
References updateQuantity().
Referenced by updateQuantity().
viewMyShifts()
String viewMyShifts (HttpSession session, Model model)
GET /buyer/my-shifts — display the buyer's assigned shifts and approved vacations.
The session attribute "user" is read directly (rather than using the Spring Security principal) to obtain the Buyer's database ID, which is then used to query shifts and vacation records.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives shifts, vacations, and dashboardLink attributes.
Returns
Thymeleaf template employee/my-shifts, or redirect:/login when no session user is found.
Definition at line 313 of file BuyerController.java.
References viewMyShifts().
Referenced by viewMyShifts().
viewProfile()
String viewProfile (HttpSession session, Model model)
GET /buyer/profile — display the buyer's personal profile page.
Reloads a fresh Employee entity from the database to avoid using a potentially stale session object. Falls back to the session entity if the DB lookup fails.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives employee, roleLabel, and dashboardLink attributes.
Returns
Thymeleaf template employee/profile, or redirect:/login when no session user is found.
Definition at line 339 of file BuyerController.java.
References viewProfile().
Referenced by viewProfile().
viewResourceLog()
String viewResourceLog (Model model)
GET /buyer/resource-log — show the full resource-take audit log.
Displays every recorded instance of an employee taking a resource from storage, giving the buyer visibility over consumption patterns.
Parameters
model Receives logs (all ResourceTakeLogStore entries).
Returns
Thymeleaf template buyer/resource-log.
Definition at line 373 of file BuyerController.java.
References viewResourceLog().
Referenced by viewResourceLog().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/BuyerController.java