VIX Health System: ContactController Class Reference
ContactController Class Reference
Controller for the public contact form — no base URL prefix.
Public Member Functions
String contact (Model model)
GET /contact — render the contact form page.
String submitContact (@RequestParam String name, @RequestParam String email, @RequestParam String message, RedirectAttributes redirectAttributes)
POST /contact/submit — log a contact-form submission and redirect with a confirmation.
Detailed Description
Controller for the public contact form — no base URL prefix.
Presents a simple contact form and handles its submission. In the current implementation the message is logged to the application log rather than forwarded to an email service; this is a deliberate placeholder that keeps the demo self-contained without requiring SMTP configuration.
Definition at line 21 of file ContactController.java.
Member Function Documentation
contact()
String contact (Model model)
GET /contact — render the contact form page.
Parameters
model Receives pageTitle.
Returns
Thymeleaf template site/contact.
Definition at line 36 of file ContactController.java.
References contact().
Referenced by contact().
submitContact()
String submitContact (@RequestParam String name, @RequestParam String email, @RequestParam String message, RedirectAttributes redirectAttributes)
POST /contact/submit — log a contact-form submission and redirect with a confirmation.
The message content is currently written to the application log only. A real deployment would forward the message to the hospital's support mailbox here instead. The redirect-after-POST pattern prevents duplicate submissions on browser reload.
Parameters
name Submitter's display name.
email Submitter's email address for follow-up.
message Free-text message body.
redirectAttributes Flash attribute successMessage shown on the contact page after the redirect.
Returns
Redirect to /contact.
Definition at line 61 of file ContactController.java.
References submitContact().
Referenced by submitContact().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/site/ContactController.java