VIX Health System: InternationRoom Class Reference
InternationRoom Class Reference
Represents an inpatient room used for patient hospitalization.
Public Member Functions
InternationRoom ()
Default constructor required by JPA.
InternationRoom (String number, int nBeds)
Creates an inpatient room with a specified number of beds.
int getNFreeBeds ()
Returns the number of currently available beds.
BedStatus getBedStatus ()
Returns the current bed availability status derived from occupancy.
void addPatient (Patient p) throws Exception
Admits a patient to the room.
boolean hasPatient (Patient p)
Checks whether a patient is currently admitted.
void removePatient (Patient p) throws Exception
Removes a patient from the room.
Public Member Functions inherited from Room
Room ()
Default constructor required by JPA.
Room (String number)
Creates a room with the specified room number.
Detailed Description
Represents an inpatient room used for patient hospitalization.
An inpatient room contains a fixed number of beds and can host multiple patients simultaneously.
Patients are linked through the RoomPatients table.
See also
Room
Patient
Definition at line 22 of file InternationRoom.java.
Constructor & Destructor Documentation
InternationRoom()
InternationRoom (String number, int nBeds)
Creates an inpatient room with a specified number of beds.
Parameters
number the room number
nBeds the total number of beds
Definition at line 53 of file InternationRoom.java.
Member Function Documentation
getNFreeBeds()
int getNFreeBeds ()
Returns the number of currently available beds.
Returns
free bed count
Definition at line 89 of file InternationRoom.java.
Referenced by RoomService.admitPatient(), getBedStatus(), Hospital.getFreeRoomsForPatients(), and RoomService.getTotalAvailableBeds().
getBedStatus()
BedStatus getBedStatus ()
Returns the current bed availability status derived from occupancy.
FREE if at least one bed is available; OCCUPIED if the room is full.
Definition at line 124 of file InternationRoom.java.
References BedStatus.FREE, getNFreeBeds(), and BedStatus.OCCUPIED.
addPatient()
void addPatient (Patient p) throws Exception
Admits a patient to the room.
Parameters
p the patient to admit
Exceptions
Exception if the room is already full
Definition at line 138 of file InternationRoom.java.
hasPatient()
boolean hasPatient (Patient p)
Checks whether a patient is currently admitted.
Parameters
p the patient to search for
Returns
true if the patient is present, false otherwise
Definition at line 153 of file InternationRoom.java.
Referenced by RoomService.dismissPatient(), Hospital.findPatientInRoom(), and removePatient().
removePatient()
void removePatient (Patient p) throws Exception
Removes a patient from the room.
Parameters
p the patient to remove
Exceptions
Exception if the patient is not present
Definition at line 163 of file InternationRoom.java.
References hasPatient().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/facility/InternationRoom.java