VIX Health System: Appointment Class Reference
Appointment Class Reference
Represents a scheduled appointment between a patient and a medical specialist.
Public Member Functions
Appointment ()
Default constructor required for JSON deserialization.
Appointment (int id, LocalDateTime dateTime, int duration, String notes)
Creates an appointment with basic scheduling details.
Appointment (LocalDateTime dateTime, int duration, String notes, Patient patient, MedicalSpecialist medicalSpecialist)
Creates a full appointment with patient and specialist information.
PaymentStatus getPaymentStatus ()
Returns the payment status enum.
boolean isPaid ()
Returns whether the appointment has been paid (boolean convenience getter).
String getStatus ()
Returns the current lifecycle status as a String (backward-compatible for templates and controllers).
AppointmentStatus getStatusEnum ()
Returns the current lifecycle status enum.
void setStatus (String status)
Sets the lifecycle status from a String (backward-compatible).
void setStatus (AppointmentStatus status)
Sets the lifecycle status using the enum.
boolean isActive ()
Checks whether the appointment is currently active.
boolean isCancellable ()
Checks whether the appointment can be cancelled.
void cancel ()
Cancels this appointment.
void reschedule (LocalDateTime newDateTime)
Reschedules this appointment to a new date and time.
void awaitPayment ()
Marks this appointment as pending payment after initial booking.
void pay ()
Records a successful payment and confirms the appointment.
Detailed Description
Represents a scheduled appointment between a patient and a medical specialist.
Appointments are stored as JSON (appointments.json), not in the SQL database. Each appointment has a status that tracks its lifecycle.
Possible status values: PENDING, CONFIRMED, CANCELLED, RESCHEDULED, COMPLETED.
See also
Patient
MedicalSpecialist
Definition at line 24 of file Appointment.java.
Constructor & Destructor Documentation
Appointment() [1/2]
Appointment (int id, LocalDateTime dateTime, int duration, String notes)
Creates an appointment with basic scheduling details.
Status defaults to CONFIRMED.
Parameters
id the appointment identifier
dateTime the scheduled date and time
duration the duration in minutes
notes optional notes
Definition at line 85 of file Appointment.java.
References AppointmentStatus.CONFIRMED.
Appointment() [2/2]
Appointment (LocalDateTime dateTime, int duration, String notes, Patient patient, MedicalSpecialist medicalSpecialist)
Creates a full appointment with patient and specialist information.
Status defaults to CONFIRMED.
Parameters
dateTime the scheduled date and time
duration the duration in minutes
notes optional notes
patient the attending patient
medicalSpecialist the conducting specialist
Definition at line 108 of file Appointment.java.
References AppointmentStatus.CONFIRMED.
Member Function Documentation
isPaid()
boolean isPaid ()
Returns whether the appointment has been paid (boolean convenience getter).
Excluded from JSON serialization : paymentStatus field is the canonical form.
Definition at line 271 of file Appointment.java.
References PaymentStatus.PAID.
isActive()
boolean isActive ()
Checks whether the appointment is currently active.
An appointment is active if it has not been cancelled or completed.
Returns
true if the appointment is active, false otherwise
Definition at line 323 of file Appointment.java.
References AppointmentStatus.CANCELLED, and AppointmentStatus.COMPLETED.
Referenced by reschedule().
cancel()
void cancel ()
Cancels this appointment.
Exceptions
IllegalStateException if the appointment cannot be cancelled
Definition at line 344 of file Appointment.java.
References AppointmentStatus.CANCELLED, and isCancellable().
Referenced by PatientAppointmentController.cancelAppointment(), and AppointmentService.cancelAppointment().
reschedule()
void reschedule (LocalDateTime newDateTime)
Reschedules this appointment to a new date and time.
Parameters
newDateTime the new scheduled date and time
Exceptions
IllegalStateException if the appointment is cancelled or completed
Definition at line 359 of file Appointment.java.
References isActive(), and AppointmentStatus.RESCHEDULED.
Referenced by PatientAppointmentController.rescheduleAppointment(), and AppointmentService.rescheduleAppointment().
pay()
void pay ()
Records a successful payment and confirms the appointment.
Exceptions
IllegalStateException if the appointment is already paid or cancelled
Definition at line 382 of file Appointment.java.
References AppointmentStatus.CANCELLED, AppointmentStatus.CONFIRMED, and PaymentStatus.PAID.
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/medical/Appointment.java