VIX Health System: Patient Class Reference
Patient Class Reference
Represents a patient in the VIX Health System.
Public Member Functions
Patient ()
Default constructor required by JPA.
Patient (String fiscalCode, MedicalRecord medicalRecord)
Creates a Patient with the specified fiscal code and medical record.
void setFiscalCode (String fiscalCode)
Sets the patient's Italian fiscal code.
Role getSystemRole ()
Returns the system authentication role for patients.
Appointment makeAppointment (MedicalSpecialist m, LocalDateTime dt)
Creates and registers a new appointment for this patient with a specialist.
void rescheduleAppointment (LocalDateTime dtOld, LocalDateTime dtNew)
Reschedules an existing appointment to a new date and time.
void cancelAppointment (LocalDateTime dt)
Cancels and removes the appointment scheduled at the specified date and time.
void deleteAccount ()
Deletes the patient's account by clearing all appointments and removing the reference to the medical record.
Public Member Functions inherited from Person
Person ()
Default constructor required by JPA.
Person (String name, String surname, LocalDate birthDate, String birthPlace, char gender, String email, String phoneNumber)
Creates a Person with the specified personal and contact information.
int getAge ()
Calculates the current age based on the date of birth.
Detailed Description
Represents a patient in the VIX Health System.
A patient has a unique fiscal code, personal information inherited from Person, one medical record and a list of appointments.
Appointment-management logic is kept inside this class.
See also
Person
MedicalRecord
Appointment
Definition at line 30 of file Patient.java.
Constructor & Destructor Documentation
Patient()
Patient (String fiscalCode, MedicalRecord medicalRecord)
Creates a Patient with the specified fiscal code and medical record.
Parameters
fiscalCode the Italian fiscal code (16 characters, unique)
medicalRecord the patient's medical record
Definition at line 79 of file Patient.java.
Member Function Documentation
setFiscalCode()
void setFiscalCode (String fiscalCode)
Sets the patient's Italian fiscal code.
Parameters
fiscalCode the fiscal code to set (must be 16 characters, unique)
Definition at line 126 of file Patient.java.
Referenced by PatientService.deletePatient(), and PatientService.updatePatient().
makeAppointment()
Appointment makeAppointment (MedicalSpecialist m, LocalDateTime dt)
Creates and registers a new appointment for this patient with a specialist.
Parameters
m the medical specialist conducting the appointment
dt the scheduled date and time
Returns
the newly created appointment
Definition at line 190 of file Patient.java.
Referenced by Secretary.makeAppointmentForPatient().
rescheduleAppointment()
void rescheduleAppointment (LocalDateTime dtOld, LocalDateTime dtNew)
Reschedules an existing appointment to a new date and time.
Only the first appointment matching the old date is updated.
Parameters
dtOld the current date and time of the appointment to reschedule
dtNew the new date and time
Definition at line 208 of file Patient.java.
Referenced by Secretary.rescheduleAppointmentForPatient().
cancelAppointment()
void cancelAppointment (LocalDateTime dt)
Cancels and removes the appointment scheduled at the specified date and time.
Parameters
dt the date and time of the appointment to cancel
Definition at line 222 of file Patient.java.
Referenced by Secretary.cancelAppointmentForPatient().
deleteAccount()
void deleteAccount ()
Deletes the patient's account by clearing all appointments and removing the reference to the medical record.
Actual removal from the database is handled by the service layer.
Definition at line 232 of file Patient.java.
Referenced by PatientService.deletePatient().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/model/person/Patient.java