VIX Health System: SecretaryController Class Reference
SecretaryController Class Reference
Controller for Secretary staff members — base URL /secretary.
Public Member Functions
String dashboard (HttpSession session, Model model)
GET /secretary/dashboard — render the secretary's overview dashboard.
String viewAllRooms (Model model)
GET /secretary/rooms — list all inpatient rooms with their current occupancy.
String viewAvailableRooms (Model model)
GET /secretary/rooms/available — list only rooms with free beds.
String admitPatient (@RequestParam Long patientId, @RequestParam Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/patients/admit — admit a patient to a specific room.
String dismissPatient (@RequestParam Long patientId, @RequestParam Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/patients/dismiss — discharge a patient from their room.
String manageAppointments (Model model)
GET /secretary/appointments — display all appointments with management controls.
String bookAppointmentForPatient (@RequestParam Long patientId, @RequestParam Long specialistId, @RequestParam String dateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/appointments/book-for-patient — book an appointment on behalf of a patient.
String confirmAppointment (@PathVariable int appointmentId, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/confirm — set an appointment status to CONFIRMED.
String cancelAppointment (@PathVariable int appointmentId, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/cancel — cancel an appointment via the domain method.
String rescheduleAppointment (@PathVariable int appointmentId, @RequestParam String newDateTime, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/reschedule — move an appointment to a new date/time.
String viewMyShifts (HttpSession session, Model model)
GET /secretary/my-shifts — display the secretary's assigned shifts and approved vacations.
String viewProfile (HttpSession session, Model model)
GET /secretary/profile — display the secretary's personal profile page.
String showPatientSearchForm (Model model)
GET /secretary/patients/search — render the patient search form.
String viewPatientProfile (@PathVariable Long id, Model model)
GET /secretary/patients/{id} — display a patient's basic profile.
String searchPatients (@RequestParam String query, Model model)
POST /secretary/patients/search — execute a patient search and display results.
Detailed Description
Controller for Secretary staff members — base URL /secretary.
Secretaries handle the administrative side of patient flow and appointment management. This controller covers room management (UC21), patient admission and dismissal (UC22, UC23), appointment booking/confirmation/cancellation/ rescheduling (UC14, UC15, UC16), patient search, and the secretary's own shift and profile pages.
Only accessible to users with ROLE_SECRETARY.
See also
RoomService
AppointmentService
PatientService
AuditService
Definition at line 49 of file SecretaryController.java.
Member Function Documentation
dashboard()
String dashboard (HttpSession session, Model model)
GET /secretary/dashboard — render the secretary's overview dashboard.
Resolves the secretary's department name by reloading a fresh entity from the database (avoiding lazy-loading failures on the detached session entity). Populates room and appointment summary counts.
Parameters
session HTTP session carrying the "user" Employee attribute, used to look up the secretary's assigned department name.
model Receives departmentName, totalRooms, availableRooms, totalAppointments, and totalAvailableBeds attributes.
Returns
Thymeleaf template secretary/dashboard.
Definition at line 99 of file SecretaryController.java.
References dashboard().
Referenced by dashboard().
viewAllRooms()
String viewAllRooms (Model model)
GET /secretary/rooms — list all inpatient rooms with their current occupancy.
Parameters
model Receives rooms and patients (for the admission form selects).
Returns
Thymeleaf template secretary/rooms.
Definition at line 137 of file SecretaryController.java.
References viewAllRooms().
Referenced by viewAllRooms().
viewAvailableRooms()
String viewAvailableRooms (Model model)
GET /secretary/rooms/available — list only rooms with free beds.
Parameters
model Receives rooms (available InternationRooms only), patients, and isAvailableView=true.
Returns
Thymeleaf template secretary/rooms.
Definition at line 156 of file SecretaryController.java.
References viewAvailableRooms().
Referenced by viewAvailableRooms().
admitPatient()
String admitPatient (@RequestParam Long patientId, @RequestParam Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/patients/admit — admit a patient to a specific room.
Delegates to RoomService#admitPatient via the Secretary domain object (resolved from session) and writes an audit entry.
Parameters
patientId Database ID of the patient to admit.
roomId Database ID of the target inpatient room.
session HTTP session; used to resolve the Secretary domain object so the business rule check inside the model runs correctly.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/rooms.
Definition at line 186 of file SecretaryController.java.
References admitPatient().
Referenced by admitPatient().
dismissPatient()
String dismissPatient (@RequestParam Long patientId, @RequestParam Long roomId, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/patients/dismiss — discharge a patient from their room.
Parameters
patientId Database ID of the patient to discharge.
roomId Database ID of the room the patient is currently in.
session HTTP session; used to resolve the Secretary domain object.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/rooms.
Definition at line 213 of file SecretaryController.java.
References dismissPatient().
Referenced by dismissPatient().
manageAppointments()
String manageAppointments (Model model)
GET /secretary/appointments — display all appointments with management controls.
Parameters
model Receives appointments, patients, and specialists for the booking form dropdowns.
Returns
Thymeleaf template secretary/manage-appointments.
Definition at line 242 of file SecretaryController.java.
References manageAppointments().
Referenced by manageAppointments().
bookAppointmentForPatient()
String bookAppointmentForPatient (@RequestParam Long patientId, @RequestParam Long specialistId, @RequestParam String dateTime, HttpSession session, RedirectAttributes redirectAttributes)
POST /secretary/appointments/book-for-patient — book an appointment on behalf of a patient.
Parameters
patientId Database ID of the patient.
specialistId Database ID of the target MedicalSpecialist.
dateTime Appointment datetime string (yyyy-MM-ddTHH:mm).
session HTTP session; used to resolve the Secretary domain object required by AppointmentService#bookForSecretary.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/appointments.
Definition at line 267 of file SecretaryController.java.
References bookAppointmentForPatient().
Referenced by bookAppointmentForPatient().
confirmAppointment()
String confirmAppointment (@PathVariable int appointmentId, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/confirm — set an appointment status to CONFIRMED.
Parameters
appointmentId Numeric ID of the appointment to confirm.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/appointments.
Definition at line 308 of file SecretaryController.java.
References confirmAppointment(), and Appointment.setStatus().
Referenced by confirmAppointment().
cancelAppointment()
String cancelAppointment (@PathVariable int appointmentId, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/cancel — cancel an appointment via the domain method.
Parameters
appointmentId Numeric ID of the appointment to cancel.
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/appointments.
Definition at line 334 of file SecretaryController.java.
References cancelAppointment().
Referenced by cancelAppointment().
rescheduleAppointment()
String rescheduleAppointment (@PathVariable int appointmentId, @RequestParam String newDateTime, RedirectAttributes redirectAttributes)
POST /secretary/appointments/{appointmentId}/reschedule — move an appointment to a new date/time.
Parameters
appointmentId Numeric ID of the appointment to reschedule.
newDateTime New datetime string (yyyy-MM-ddTHH:mm).
redirectAttributes Flash attributes for the redirect.
Returns
Redirect to /secretary/appointments.
Definition at line 358 of file SecretaryController.java.
References rescheduleAppointment().
Referenced by rescheduleAppointment().
viewMyShifts()
String viewMyShifts (HttpSession session, Model model)
GET /secretary/my-shifts — display the secretary's assigned shifts and approved vacations.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives shifts, vacations, and dashboardLink.
Returns
Thymeleaf template employee/my-shifts, or redirect:/login when no session user is found.
Definition at line 391 of file SecretaryController.java.
References viewMyShifts().
Referenced by viewMyShifts().
viewProfile()
String viewProfile (HttpSession session, Model model)
GET /secretary/profile — display the secretary's personal profile page.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives employee, roleLabel, and dashboardLink.
Returns
Thymeleaf template employee/profile, or redirect:/login when no session user is found.
Definition at line 412 of file SecretaryController.java.
References viewProfile().
Referenced by viewProfile().
showPatientSearchForm()
String showPatientSearchForm (Model model)
GET /secretary/patients/search — render the patient search form.
Parameters
model Receives pageTitle and currentPage attributes.
Returns
Thymeleaf template secretary/patient-search.
Definition at line 443 of file SecretaryController.java.
References showPatientSearchForm().
Referenced by showPatientSearchForm().
viewPatientProfile()
String viewPatientProfile (@PathVariable Long id, Model model)
GET /secretary/patients/{id} — display a patient's basic profile.
Parameters
id Database ID of the patient.
model Receives patient attributes.
Returns
Thymeleaf template secretary/patient-profile, or redirect to /secretary/patients/search when the patient is not found.
Definition at line 458 of file SecretaryController.java.
References viewPatientProfile().
Referenced by viewPatientProfile().
searchPatients()
String searchPatients (@RequestParam String query, Model model)
POST /secretary/patients/search — execute a patient search and display results.
Parameters
query Free-text search term (name, fiscal code, etc.).
model Receives patients list and echoes query.
Returns
Thymeleaf template secretary/patient-search-results.
Definition at line 478 of file SecretaryController.java.
References searchPatients().
Referenced by searchPatients().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/SecretaryController.java