VIX Health System: JsonVacationRepository Class Reference
JsonVacationRepository Class Reference
JSON-file-backed repository for VacationRequest entities.
Public Member Functions
JsonVacationRepository ()
Configures the Jackson mapper with Java 8 date/time support.
List< VacationRequest > findAll ()
Returns all vacation requests from the JSON file.
void saveAll (List< VacationRequest > requests)
Overwrites the JSON file with the complete vacation request list.
Optional< VacationRequest > findById (int id)
Finds a vacation request by its numeric ID.
VacationRequest save (VacationRequest request)
Persists a vacation request, inserting or replacing by ID.
void deleteById (int id)
Removes the vacation request with the given ID.
Detailed Description
JSON-file-backed repository for VacationRequest entities.
Persists employee vacation requests to src/main/resources/storage/vacations.json. Auto-assigns sequential integer IDs on first save, and replaces existing records when an ID already exists.
See also
com.nvivx.vixhealthsystem.model.staff.VacationRequest
JsonShiftRepository
Definition at line 25 of file JsonVacationRepository.java.
Member Function Documentation
findAll()
List< VacationRequest > findAll ()
Returns all vacation requests from the JSON file.
Returns
mutable list of all requests; never null, empty if file is absent
Exceptions
RuntimeException if the file cannot be parsed
Definition at line 60 of file JsonVacationRepository.java.
Referenced by deleteById(), findById(), and save().
saveAll()
void saveAll (List< VacationRequest > requests)
Overwrites the JSON file with the complete vacation request list.
Parameters
requests replacement list; must not be null
Exceptions
RuntimeException if the file cannot be written
Definition at line 76 of file JsonVacationRepository.java.
Referenced by deleteById(), and save().
findById()
Optional< VacationRequest > findById (int id)
Finds a vacation request by its numeric ID.
Parameters
id the vacation request ID
Returns
an Optional containing the request, or empty if not found
Definition at line 92 of file JsonVacationRepository.java.
References findAll().
save()
VacationRequest save (VacationRequest request)
Persists a vacation request, inserting or replacing by ID.
Assigns a new sequential ID when request.getId() == 0.
Parameters
request the request to persist; must not be null
Returns
the same request with its ID populated
Definition at line 104 of file JsonVacationRepository.java.
References findAll(), and saveAll().
deleteById()
void deleteById (int id)
Removes the vacation request with the given ID.
No-op if the ID does not exist.
Parameters
id the vacation request ID to remove
Definition at line 125 of file JsonVacationRepository.java.
References findAll(), and saveAll().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/repository/JsonVacationRepository.java