VIX Health System: JsonAppointmentRepository Class Reference
JsonAppointmentRepository Class Reference
JSON-file-backed repository for Appointment entities.
Public Member Functions
JsonAppointmentRepository ()
Configures the Jackson mapper with Java 8 date/time support.
List< Appointment > findAll ()
Returns all appointments stored in the JSON file.
void saveAll (List< Appointment > appointments)
Overwrites the JSON file with the given appointment list.
Appointment findById (int id)
Finds a single appointment by its numeric ID.
Appointment save (Appointment appointment)
Persists an appointment, inserting or replacing based on ID.
void deleteById (int id)
Removes the appointment with the given ID from the JSON store.
Detailed Description
JSON-file-backed repository for Appointment entities.
Persists appointments to src/main/resources/storage/appointments.json instead of a relational database, keeping scheduling data separate from the H2/PostgreSQL schema. Auto-assigns sequential integer IDs on first save.
See also
JsonAuditLogRepository
vixhealthsystem.model.medical.Appointment
Definition at line 25 of file JsonAppointmentRepository.java.
Constructor & Destructor Documentation
JsonAppointmentRepository()
JsonAppointmentRepository ()
Configures the Jackson mapper with Java 8 date/time support.
Registers JavaTimeModule and disables timestamp-based serialisation so that dates are stored as human-readable ISO-8601 strings.
Definition at line 47 of file JsonAppointmentRepository.java.
Member Function Documentation
findAll()
List< Appointment > findAll ()
Returns all appointments stored in the JSON file.
Returns an empty list when the file does not yet exist or is empty.
Returns
mutable list of all appointments; never null
Exceptions
RuntimeException if the file cannot be parsed
Definition at line 65 of file JsonAppointmentRepository.java.
Referenced by deleteById(), findById(), and save().
saveAll()
void saveAll (List< Appointment > appointments)
Overwrites the JSON file with the given appointment list.
Creates parent directories if they do not exist.
Parameters
appointments complete replacement list; must not be null
Exceptions
RuntimeException if the file cannot be written
Definition at line 83 of file JsonAppointmentRepository.java.
Referenced by deleteById(), and save().
findById()
Appointment findById (int id)
Finds a single appointment by its numeric ID.
Parameters
id appointment ID
Returns
the matching appointment, or null if not found
Definition at line 99 of file JsonAppointmentRepository.java.
References findAll().
save()
Appointment save (Appointment appointment)
Persists an appointment, inserting or replacing based on ID.
When appointment.getId() == 0 a new sequential ID is assigned. Otherwise the existing record with the same ID is replaced.
Parameters
appointment the appointment to persist; must not be null
Returns
the same appointment with its ID populated
Definition at line 112 of file JsonAppointmentRepository.java.
References findAll(), and saveAll().
deleteById()
void deleteById (int id)
Removes the appointment with the given ID from the JSON store.
No-op if the ID does not exist.
Parameters
id appointment ID to remove
Definition at line 133 of file JsonAppointmentRepository.java.
References findAll(), and saveAll().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/repository/JsonAppointmentRepository.java