VIX Health System: LegalController Class Reference
LegalController Class Reference
Controller for public legal and compliance pages — no base URL prefix.
Public Member Functions
String privacy ()
GET /privacy — render the privacy policy page.
String gdpr ()
GET /gdpr — render the GDPR data processing notice.
String terms ()
GET /terms — render the terms of use page.
String accessibility ()
GET /accessibility — render the accessibility statement.
Detailed Description
Controller for public legal and compliance pages — no base URL prefix.
Serves the static legal documents required by Italian and EU law: privacy policy, GDPR notice, terms of use, and accessibility statement. Each handler simply routes to the corresponding Thymeleaf fragment; no dynamic data is needed.
Definition at line 15 of file LegalController.java.
Member Function Documentation
privacy()
String privacy ()
GET /privacy — render the privacy policy page.
Returns
Thymeleaf template fragments/footer/privacy-policy.
Definition at line 26 of file LegalController.java.
References privacy().
Referenced by privacy().
gdpr()
String gdpr ()
GET /gdpr — render the GDPR data processing notice.
Returns
Thymeleaf template fragments/footer/gdpr.
Definition at line 33 of file LegalController.java.
References gdpr().
Referenced by gdpr().
terms()
String terms ()
GET /terms — render the terms of use page.
Returns
Thymeleaf template fragments/footer/terms-of-use.
Definition at line 40 of file LegalController.java.
References terms().
Referenced by terms().
accessibility()
String accessibility ()
GET /accessibility — render the accessibility statement.
Returns
Thymeleaf template fragments/footer/accessibility.
Definition at line 47 of file LegalController.java.
References accessibility().
Referenced by accessibility().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/site/LegalController.java