VIX Health System: TechnicianController Class Reference
TechnicianController Class Reference
Controller for Technician staff members — base URL /technician.
Public Member Functions
String dashboard (Model model)
GET /technician/dashboard — render the technician's overview dashboard.
String viewAllMachines (Model model)
GET /technician/machines — list all machines in the hospital fleet.
String viewFaultyMachines (HttpSession session, Model model)
GET /technician/machines/faulty — list only machines with FAULTY status.
String viewMaintenanceMachines (Model model)
GET /technician/machines/maintenance — list machines currently under maintenance.
String updateMachineStatus (@RequestParam Long machineId, @RequestParam String status, Model model)
POST /technician/machines/update-status — change the operational status of a machine.
String viewAlerts (Model model)
GET /technician/alerts — display all active machine fault alerts.
String viewMyShifts (HttpSession session, Model model)
GET /technician/my-shifts — display the technician's assigned shifts and approved vacations.
String viewProfile (HttpSession session, Model model)
GET /technician/profile — display the technician's personal profile page.
String viewMaintenanceHistory (Model model)
GET /technician/machines/maintenance-history — show the full maintenance history for all machines.
String viewMachineDetails (@PathVariable Long machineId, Model model)
GET /technician/machines/{machineId} — display the details of a single machine.
String repairMachine (@PathVariable Long machineId, @RequestParam(required=false) String notes, Model model)
POST /technician/repair/{machineId} — mark a machine as repaired and set it to WORKING.
Detailed Description
Controller for Technician staff members — base URL /technician.
Technicians maintain the hospital's machinery fleet. This controller covers viewing all machines, filtering by faulty or maintenance status, updating machine status, logging repairs, viewing active alerts, and the technician's own shift and profile pages.
Only accessible to users with ROLE_TECHNICIAN.
Use cases covered: UC26 (machinery maintenance), UC27 (status updates), UC28 (alerts), UC30 (profile/shifts).
See also
MachineryService
ShiftService
VacationService
Definition at line 37 of file TechnicianController.java.
Member Function Documentation
dashboard()
String dashboard (Model model)
GET /technician/dashboard — render the technician's overview dashboard.
Parameters
model Receives totalMachines, faultyCount, maintenanceCount, alertCount, and activeAlerts.
Returns
Thymeleaf template technician/dashboard.
Definition at line 66 of file TechnicianController.java.
References dashboard().
Referenced by dashboard().
viewAllMachines()
String viewAllMachines (Model model)
GET /technician/machines — list all machines in the hospital fleet.
Parameters
model Receives machines and isFaultyView=false.
Returns
Thymeleaf template technician/machines.
Definition at line 88 of file TechnicianController.java.
References viewAllMachines().
Referenced by viewAllMachines().
viewFaultyMachines()
String viewFaultyMachines (HttpSession session, Model model)
GET /technician/machines/faulty — list only machines with FAULTY status.
Delegates to the domain method via MachineryService#getFaultyMachinesForTechnician, which applies technician-specific filtering logic. The technician domain object is resolved from the session.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives machines and isFaultyView=true.
Returns
Thymeleaf template technician/machines.
Definition at line 109 of file TechnicianController.java.
References viewFaultyMachines().
Referenced by viewFaultyMachines().
viewMaintenanceMachines()
String viewMaintenanceMachines (Model model)
GET /technician/machines/maintenance — list machines currently under maintenance.
Parameters
model Receives machines.
Returns
Thymeleaf template technician/machines.
Definition at line 127 of file TechnicianController.java.
References viewMaintenanceMachines().
Referenced by viewMaintenanceMachines().
updateMachineStatus()
String updateMachineStatus (@RequestParam Long machineId, @RequestParam String status, Model model)
POST /technician/machines/update-status — change the operational status of a machine.
Parameters
machineId Database ID of the machine to update.
status String representation of a MachineStatus enum value (e.g., "WORKING", "FAULTY", "MAINTENANCE").
model Receives a success or error message attribute.
Returns
Thymeleaf template technician/result.
Definition at line 145 of file TechnicianController.java.
References MachineStatus.FAULTY, updateMachineStatus(), and MachineStatus.WORKING.
Referenced by updateMachineStatus().
viewAlerts()
String viewAlerts (Model model)
GET /technician/alerts — display all active machine fault alerts.
Parameters
model Receives alerts and alertCount.
Returns
Thymeleaf template technician/alerts.
Definition at line 181 of file TechnicianController.java.
References viewAlerts().
Referenced by viewAlerts().
viewMyShifts()
String viewMyShifts (HttpSession session, Model model)
GET /technician/my-shifts — display the technician's assigned shifts and approved vacations.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives shifts, vacations, and dashboardLink.
Returns
Thymeleaf template employee/my-shifts, or redirect:/login when no session user is found.
Definition at line 203 of file TechnicianController.java.
References viewMyShifts().
Referenced by viewMyShifts().
viewProfile()
String viewProfile (HttpSession session, Model model)
GET /technician/profile — display the technician's personal profile page.
Parameters
session HTTP session carrying the "user" Employee attribute.
model Receives employee, roleLabel, and dashboardLink.
Returns
Thymeleaf template employee/profile, or redirect:/login when no session user is found.
Definition at line 224 of file TechnicianController.java.
References viewProfile().
Referenced by viewProfile().
viewMaintenanceHistory()
String viewMaintenanceHistory (Model model)
GET /technician/machines/maintenance-history — show the full maintenance history for all machines.
Parameters
model Receives machines (all machines with their historical status records).
Returns
Thymeleaf template technician/maintenance-history.
Definition at line 281 of file TechnicianController.java.
References viewMaintenanceHistory().
Referenced by viewMaintenanceHistory().
viewMachineDetails()
String viewMachineDetails (@PathVariable Long machineId, Model model)
GET /technician/machines/{machineId} — display the details of a single machine.
Parameters
machineId Database ID of the machine to display.
model Receives machine attribute.
Returns
Thymeleaf template technician/machine-details, or technician/result with a not-found message when the ID does not exist.
Definition at line 298 of file TechnicianController.java.
References viewMachineDetails().
Referenced by viewMachineDetails().
repairMachine()
String repairMachine (@PathVariable Long machineId, @RequestParam(required=false) String notes, Model model)
POST /technician/repair/{machineId} — mark a machine as repaired and set it to WORKING.
Parameters
machineId Database ID of the machine that has been repaired.
notes Optional free-text repair notes; ignored when blank.
model Receives a success or error message attribute.
Returns
Thymeleaf template technician/result.
Definition at line 321 of file TechnicianController.java.
References repairMachine().
Referenced by repairMachine().
The documentation for this class was generated from the following file:
com/nvivx/vixhealthsystem/controllers/staff/TechnicianController.java